import type {
  ArtifactDetail,
  ArtifactListQuery,
  ArtifactSummary,
  ActivityEventSummary,
  ActivityListQuery,
  ApplicationOutcome,
  ApplicationOutcomeKind,
  ApplicationOutcomeListResponse,
  ApplicationOutcomeSource,
  ApplicationOutcomeWriteResponse,
  ApplyReviewDecision,
  ApplyReviewDecisionRequest,
  ApplyReviewDecisionResponse,
  ApplyReviewDecisionValue,
  ApplyReviewQueueItem,
  ApplyReviewQueueResponse,
  CompensationSourcePolicySummary,
  CompensationSourceRegistryResponse,
  CredentialsResponse,
  DashboardSettings,
  DashboardSummary,
  DiscoverySettings,
  DiscoverySettingsResponse,
  DiscoverySettingsUpdateRequest,
  DiscoveryFeedbackKind,
  DiscoveryFeedbackRequest,
  DiscoveryFeedbackResponse,
  DiscoveryPreviewResponse,
  EvidenceGap,
  EvidenceMapEntry,
  EvidenceMapResponse,
  EvidenceUsageRef,
  InterviewPrep,
  InterviewPrepItem,
  InterviewPrepItemKind,
  JobDetail,
  JobApplicationOutcomeListResponse,
  JobListQuery,
  JobSortField,
  JobSummary,
  ManualCaptureImportRequest,
  ManualCaptureListResponse,
  ManualApplicationOutcomeRequest,
  OutcomeSuggestion,
  OutcomeSuggestionDecisionRequest,
  OutcomeSuggestionDecisionResponse,
  OutcomeSuggestionStatus,
  PaginatedResponse,
  ProfileConfigResponse,
  QuarantineDecision,
  QuarantineListResponse,
  RoleMatchFeedbackDecisionRequest,
  RoleMatchFeedbackDecisionResponse,
  RoleMatchFeedbackListResponse,
  RoleMatchFeedbackSuggestion,
  ResumeCommentReply,
  ResumeCommentReplyRequest,
  ResumeCommentReplyResponse,
  ResumeCommentThread,
  ResumeReviewDraft,
  ResumeReviewDraftCreateRequest,
  ResumeReviewDraftResponse,
  ResumeReviewDraftRevision,
  ResumeReviewDraftRevisionResponse,
  ResumeReviewDraftRevisionSaveRequest,
  ResumeReviewEditDelta,
  ResumeReviewFeedbackListResponse,
  SettingsResponse,
  SourceLocatorDecisionRequest,
  SourceLocatorDecisionResponse,
  SourceLocatorListResponse,
  SourceRegistryEntrySummary,
  SourceRegistryListResponse,
  SourceRegistryMutationResponse,
  SourceStatePatch,
  SourceUpsertRequest,
  Stage,
  StageState,
  WorkflowRunDetail,
  WorkflowRunStatus,
  WorkflowRunStatusFilter,
  WorkflowRunSummary,
  WorkflowRunTimelineEvent,
  WorkflowRunsListQuery,
} from "@jobhunter/contracts";
import type { DomainEventUnion } from "@jobhunter/domain-types";

export type {
  ArtifactDetail,
  ArtifactListQuery,
  ArtifactSummary,
  ActivityEventSummary,
  ActivityListQuery,
  ApplicationOutcome,
  ApplicationOutcomeKind,
  ApplicationOutcomeListResponse,
  ApplicationOutcomeSource,
  ApplicationOutcomeWriteResponse,
  ApplyReviewDecision,
  ApplyReviewDecisionRequest,
  ApplyReviewDecisionResponse,
  ApplyReviewDecisionValue,
  ApplyReviewQueueItem,
  ApplyReviewQueueResponse,
  CompensationSourcePolicySummary,
  CompensationSourceRegistryResponse,
  CredentialsResponse,
  DashboardSettings,
  DashboardSummary,
  DiscoverySettings,
  DiscoverySettingsResponse,
  DiscoverySettingsUpdateRequest,
  DiscoveryFeedbackKind,
  DiscoveryFeedbackRequest,
  DiscoveryFeedbackResponse,
  DiscoveryPreviewResponse,
  EvidenceGap,
  EvidenceMapEntry,
  EvidenceMapResponse,
  EvidenceUsageRef,
  InterviewPrep,
  InterviewPrepItem,
  InterviewPrepItemKind,
  JobDetail,
  JobApplicationOutcomeListResponse,
  JobListQuery,
  JobSortField,
  JobSummary,
  ManualCaptureImportRequest,
  ManualCaptureListResponse,
  ManualApplicationOutcomeRequest,
  OutcomeSuggestion,
  OutcomeSuggestionDecisionRequest,
  OutcomeSuggestionDecisionResponse,
  OutcomeSuggestionStatus,
  PaginatedResponse,
  ProfileConfigResponse,
  QuarantineDecision,
  QuarantineListResponse,
  RoleMatchFeedbackDecisionRequest,
  RoleMatchFeedbackDecisionResponse,
  RoleMatchFeedbackListResponse,
  RoleMatchFeedbackSuggestion,
  ResumeCommentReply,
  ResumeCommentReplyRequest,
  ResumeCommentReplyResponse,
  ResumeCommentThread,
  ResumeReviewDraft,
  ResumeReviewDraftCreateRequest,
  ResumeReviewDraftResponse,
  ResumeReviewDraftRevision,
  ResumeReviewDraftRevisionResponse,
  ResumeReviewDraftRevisionSaveRequest,
  ResumeReviewEditDelta,
  ResumeReviewFeedbackListResponse,
  SettingsResponse,
  SourceLocatorDecisionRequest,
  SourceLocatorDecisionResponse,
  SourceLocatorListResponse,
  SourceRegistryEntrySummary,
  SourceRegistryListResponse,
  SourceRegistryMutationResponse,
  SourceStatePatch,
  SourceUpsertRequest,
  Stage,
  StageState,
  WorkflowRunDetail,
  WorkflowRunStatus,
  WorkflowRunStatusFilter,
  WorkflowRunSummary,
  WorkflowRunTimelineEvent,
  WorkflowRunsListQuery,
};

export type JobId = string;

export type JobsListInput = Partial<Omit<JobListQuery, "stage">> & {
  readonly stage?: Stage;
  readonly stages?: readonly Stage[];
};
export type ArtifactsListInput = Partial<ArtifactListQuery>;
export type WorkflowRunsListInput = Partial<WorkflowRunsListQuery>;
export type ActivityListInput = Partial<ActivityListQuery>;

export type StageOrAll = Stage | "all";
export type StageStateOrAll = StageState | "all";

export type KnownDomainEvent = DomainEventUnion;
export type KnownDomainEventType = KnownDomainEvent["eventType"];
