/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as RunsRouteImport } from "./routes/runs";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as PreferencesRouteImport } from "./routes/preferences";
import { Route as PipelinesRouteImport } from "./routes/pipelines";
import { Route as JobsRouteImport } from "./routes/jobs";
import { Route as DiscoveryRouteImport } from "./routes/discovery";
import { Route as DebugRouteImport } from "./routes/debug";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as ArtifactsRouteImport } from "./routes/artifacts";
import { Route as ApplyReviewRouteImport } from "./routes/apply-review";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SettingsIndexRouteImport } from "./routes/settings.index";
import { Route as RunsIndexRouteImport } from "./routes/runs.index";
import { Route as ProfileIndexRouteImport } from "./routes/profile.index";
import { Route as JobsIndexRouteImport } from "./routes/jobs.index";
import { Route as ArtifactsIndexRouteImport } from "./routes/artifacts.index";
import { Route as SpikesTableFiltersRouteImport } from "./routes/spikes.table-filters";
import { Route as SettingsCredentialsRouteImport } from "./routes/settings.credentials";
import { Route as RunsRunIdRouteImport } from "./routes/runs.$runId";
import { Route as ProfileImportRouteImport } from "./routes/profile.import";
import { Route as JobsJobIdRouteImport } from "./routes/jobs.$jobId";
import { Route as ArtifactsArtifactIdRouteImport } from "./routes/artifacts.$artifactId";
import { Route as ActivityEventIdRouteImport } from "./routes/activity.$eventId";
import { Route as ProfileImportUploadRouteImport } from "./routes/profile.import.upload";
import { Route as ProfileImportPreviewRouteImport } from "./routes/profile.import.preview";
import { Route as ProfileImportConfirmRouteImport } from "./routes/profile.import.confirm";
import { Route as JobsJobIdRunRunIdRouteImport } from "./routes/jobs.$jobId.run.$runId";

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const RunsRoute = RunsRouteImport.update({
  id: "/runs",
  path: "/runs",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any);
const PreferencesRoute = PreferencesRouteImport.update({
  id: "/preferences",
  path: "/preferences",
  getParentRoute: () => rootRouteImport,
} as any);
const PipelinesRoute = PipelinesRouteImport.update({
  id: "/pipelines",
  path: "/pipelines",
  getParentRoute: () => rootRouteImport,
} as any);
const JobsRoute = JobsRouteImport.update({
  id: "/jobs",
  path: "/jobs",
  getParentRoute: () => rootRouteImport,
} as any);
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: "/discovery",
  path: "/discovery",
  getParentRoute: () => rootRouteImport,
} as any);
const DebugRoute = DebugRouteImport.update({
  id: "/debug",
  path: "/debug",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: "/artifacts",
  path: "/artifacts",
  getParentRoute: () => rootRouteImport,
} as any);
const ApplyReviewRoute = ApplyReviewRouteImport.update({
  id: "/apply-review",
  path: "/apply-review",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SettingsRoute,
} as any);
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => RunsRoute,
} as any);
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProfileRoute,
} as any);
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => JobsRoute,
} as any);
const ArtifactsIndexRoute = ArtifactsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ArtifactsRoute,
} as any);
const SpikesTableFiltersRoute = SpikesTableFiltersRouteImport.update({
  id: "/spikes/table-filters",
  path: "/spikes/table-filters",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsCredentialsRoute = SettingsCredentialsRouteImport.update({
  id: "/credentials",
  path: "/credentials",
  getParentRoute: () => SettingsRoute,
} as any);
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: "/$runId",
  path: "/$runId",
  getParentRoute: () => RunsRoute,
} as any);
const ProfileImportRoute = ProfileImportRouteImport.update({
  id: "/import",
  path: "/import",
  getParentRoute: () => ProfileRoute,
} as any);
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: "/$jobId",
  path: "/$jobId",
  getParentRoute: () => JobsRoute,
} as any);
const ArtifactsArtifactIdRoute = ArtifactsArtifactIdRouteImport.update({
  id: "/$artifactId",
  path: "/$artifactId",
  getParentRoute: () => ArtifactsRoute,
} as any);
const ActivityEventIdRoute = ActivityEventIdRouteImport.update({
  id: "/activity/$eventId",
  path: "/activity/$eventId",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileImportUploadRoute = ProfileImportUploadRouteImport.update({
  id: "/upload",
  path: "/upload",
  getParentRoute: () => ProfileImportRoute,
} as any);
const ProfileImportPreviewRoute = ProfileImportPreviewRouteImport.update({
  id: "/preview",
  path: "/preview",
  getParentRoute: () => ProfileImportRoute,
} as any);
const ProfileImportConfirmRoute = ProfileImportConfirmRouteImport.update({
  id: "/confirm",
  path: "/confirm",
  getParentRoute: () => ProfileImportRoute,
} as any);
const JobsJobIdRunRunIdRoute = JobsJobIdRunRunIdRouteImport.update({
  id: "/run/$runId",
  path: "/run/$runId",
  getParentRoute: () => JobsJobIdRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/apply-review": typeof ApplyReviewRoute;
  "/artifacts": typeof ArtifactsRouteWithChildren;
  "/dashboard": typeof DashboardRoute;
  "/debug": typeof DebugRoute;
  "/discovery": typeof DiscoveryRoute;
  "/jobs": typeof JobsRouteWithChildren;
  "/pipelines": typeof PipelinesRoute;
  "/preferences": typeof PreferencesRoute;
  "/profile": typeof ProfileRouteWithChildren;
  "/runs": typeof RunsRouteWithChildren;
  "/settings": typeof SettingsRouteWithChildren;
  "/activity/$eventId": typeof ActivityEventIdRoute;
  "/artifacts/$artifactId": typeof ArtifactsArtifactIdRoute;
  "/jobs/$jobId": typeof JobsJobIdRouteWithChildren;
  "/profile/import": typeof ProfileImportRouteWithChildren;
  "/runs/$runId": typeof RunsRunIdRoute;
  "/settings/credentials": typeof SettingsCredentialsRoute;
  "/spikes/table-filters": typeof SpikesTableFiltersRoute;
  "/artifacts/": typeof ArtifactsIndexRoute;
  "/jobs/": typeof JobsIndexRoute;
  "/profile/": typeof ProfileIndexRoute;
  "/runs/": typeof RunsIndexRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/profile/import/confirm": typeof ProfileImportConfirmRoute;
  "/profile/import/preview": typeof ProfileImportPreviewRoute;
  "/profile/import/upload": typeof ProfileImportUploadRoute;
  "/jobs/$jobId/run/$runId": typeof JobsJobIdRunRunIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/apply-review": typeof ApplyReviewRoute;
  "/dashboard": typeof DashboardRoute;
  "/debug": typeof DebugRoute;
  "/discovery": typeof DiscoveryRoute;
  "/pipelines": typeof PipelinesRoute;
  "/preferences": typeof PreferencesRoute;
  "/activity/$eventId": typeof ActivityEventIdRoute;
  "/artifacts/$artifactId": typeof ArtifactsArtifactIdRoute;
  "/jobs/$jobId": typeof JobsJobIdRouteWithChildren;
  "/profile/import": typeof ProfileImportRouteWithChildren;
  "/runs/$runId": typeof RunsRunIdRoute;
  "/settings/credentials": typeof SettingsCredentialsRoute;
  "/spikes/table-filters": typeof SpikesTableFiltersRoute;
  "/artifacts": typeof ArtifactsIndexRoute;
  "/jobs": typeof JobsIndexRoute;
  "/profile": typeof ProfileIndexRoute;
  "/runs": typeof RunsIndexRoute;
  "/settings": typeof SettingsIndexRoute;
  "/profile/import/confirm": typeof ProfileImportConfirmRoute;
  "/profile/import/preview": typeof ProfileImportPreviewRoute;
  "/profile/import/upload": typeof ProfileImportUploadRoute;
  "/jobs/$jobId/run/$runId": typeof JobsJobIdRunRunIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/apply-review": typeof ApplyReviewRoute;
  "/artifacts": typeof ArtifactsRouteWithChildren;
  "/dashboard": typeof DashboardRoute;
  "/debug": typeof DebugRoute;
  "/discovery": typeof DiscoveryRoute;
  "/jobs": typeof JobsRouteWithChildren;
  "/pipelines": typeof PipelinesRoute;
  "/preferences": typeof PreferencesRoute;
  "/profile": typeof ProfileRouteWithChildren;
  "/runs": typeof RunsRouteWithChildren;
  "/settings": typeof SettingsRouteWithChildren;
  "/activity/$eventId": typeof ActivityEventIdRoute;
  "/artifacts/$artifactId": typeof ArtifactsArtifactIdRoute;
  "/jobs/$jobId": typeof JobsJobIdRouteWithChildren;
  "/profile/import": typeof ProfileImportRouteWithChildren;
  "/runs/$runId": typeof RunsRunIdRoute;
  "/settings/credentials": typeof SettingsCredentialsRoute;
  "/spikes/table-filters": typeof SpikesTableFiltersRoute;
  "/artifacts/": typeof ArtifactsIndexRoute;
  "/jobs/": typeof JobsIndexRoute;
  "/profile/": typeof ProfileIndexRoute;
  "/runs/": typeof RunsIndexRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/profile/import/confirm": typeof ProfileImportConfirmRoute;
  "/profile/import/preview": typeof ProfileImportPreviewRoute;
  "/profile/import/upload": typeof ProfileImportUploadRoute;
  "/jobs/$jobId/run/$runId": typeof JobsJobIdRunRunIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/apply-review"
    | "/artifacts"
    | "/dashboard"
    | "/debug"
    | "/discovery"
    | "/jobs"
    | "/pipelines"
    | "/preferences"
    | "/profile"
    | "/runs"
    | "/settings"
    | "/activity/$eventId"
    | "/artifacts/$artifactId"
    | "/jobs/$jobId"
    | "/profile/import"
    | "/runs/$runId"
    | "/settings/credentials"
    | "/spikes/table-filters"
    | "/artifacts/"
    | "/jobs/"
    | "/profile/"
    | "/runs/"
    | "/settings/"
    | "/profile/import/confirm"
    | "/profile/import/preview"
    | "/profile/import/upload"
    | "/jobs/$jobId/run/$runId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/apply-review"
    | "/dashboard"
    | "/debug"
    | "/discovery"
    | "/pipelines"
    | "/preferences"
    | "/activity/$eventId"
    | "/artifacts/$artifactId"
    | "/jobs/$jobId"
    | "/profile/import"
    | "/runs/$runId"
    | "/settings/credentials"
    | "/spikes/table-filters"
    | "/artifacts"
    | "/jobs"
    | "/profile"
    | "/runs"
    | "/settings"
    | "/profile/import/confirm"
    | "/profile/import/preview"
    | "/profile/import/upload"
    | "/jobs/$jobId/run/$runId";
  id:
    | "__root__"
    | "/"
    | "/apply-review"
    | "/artifacts"
    | "/dashboard"
    | "/debug"
    | "/discovery"
    | "/jobs"
    | "/pipelines"
    | "/preferences"
    | "/profile"
    | "/runs"
    | "/settings"
    | "/activity/$eventId"
    | "/artifacts/$artifactId"
    | "/jobs/$jobId"
    | "/profile/import"
    | "/runs/$runId"
    | "/settings/credentials"
    | "/spikes/table-filters"
    | "/artifacts/"
    | "/jobs/"
    | "/profile/"
    | "/runs/"
    | "/settings/"
    | "/profile/import/confirm"
    | "/profile/import/preview"
    | "/profile/import/upload"
    | "/jobs/$jobId/run/$runId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ApplyReviewRoute: typeof ApplyReviewRoute;
  ArtifactsRoute: typeof ArtifactsRouteWithChildren;
  DashboardRoute: typeof DashboardRoute;
  DebugRoute: typeof DebugRoute;
  DiscoveryRoute: typeof DiscoveryRoute;
  JobsRoute: typeof JobsRouteWithChildren;
  PipelinesRoute: typeof PipelinesRoute;
  PreferencesRoute: typeof PreferencesRoute;
  ProfileRoute: typeof ProfileRouteWithChildren;
  RunsRoute: typeof RunsRouteWithChildren;
  SettingsRoute: typeof SettingsRouteWithChildren;
  ActivityEventIdRoute: typeof ActivityEventIdRoute;
  SpikesTableFiltersRoute: typeof SpikesTableFiltersRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/runs": {
      id: "/runs";
      path: "/runs";
      fullPath: "/runs";
      preLoaderRoute: typeof RunsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/preferences": {
      id: "/preferences";
      path: "/preferences";
      fullPath: "/preferences";
      preLoaderRoute: typeof PreferencesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pipelines": {
      id: "/pipelines";
      path: "/pipelines";
      fullPath: "/pipelines";
      preLoaderRoute: typeof PipelinesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/jobs": {
      id: "/jobs";
      path: "/jobs";
      fullPath: "/jobs";
      preLoaderRoute: typeof JobsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/discovery": {
      id: "/discovery";
      path: "/discovery";
      fullPath: "/discovery";
      preLoaderRoute: typeof DiscoveryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/debug": {
      id: "/debug";
      path: "/debug";
      fullPath: "/debug";
      preLoaderRoute: typeof DebugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/artifacts": {
      id: "/artifacts";
      path: "/artifacts";
      fullPath: "/artifacts";
      preLoaderRoute: typeof ArtifactsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/apply-review": {
      id: "/apply-review";
      path: "/apply-review";
      fullPath: "/apply-review";
      preLoaderRoute: typeof ApplyReviewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/": {
      id: "/settings/";
      path: "/";
      fullPath: "/settings/";
      preLoaderRoute: typeof SettingsIndexRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/runs/": {
      id: "/runs/";
      path: "/";
      fullPath: "/runs/";
      preLoaderRoute: typeof RunsIndexRouteImport;
      parentRoute: typeof RunsRoute;
    };
    "/profile/": {
      id: "/profile/";
      path: "/";
      fullPath: "/profile/";
      preLoaderRoute: typeof ProfileIndexRouteImport;
      parentRoute: typeof ProfileRoute;
    };
    "/jobs/": {
      id: "/jobs/";
      path: "/";
      fullPath: "/jobs/";
      preLoaderRoute: typeof JobsIndexRouteImport;
      parentRoute: typeof JobsRoute;
    };
    "/artifacts/": {
      id: "/artifacts/";
      path: "/";
      fullPath: "/artifacts/";
      preLoaderRoute: typeof ArtifactsIndexRouteImport;
      parentRoute: typeof ArtifactsRoute;
    };
    "/spikes/table-filters": {
      id: "/spikes/table-filters";
      path: "/spikes/table-filters";
      fullPath: "/spikes/table-filters";
      preLoaderRoute: typeof SpikesTableFiltersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/credentials": {
      id: "/settings/credentials";
      path: "/credentials";
      fullPath: "/settings/credentials";
      preLoaderRoute: typeof SettingsCredentialsRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/runs/$runId": {
      id: "/runs/$runId";
      path: "/$runId";
      fullPath: "/runs/$runId";
      preLoaderRoute: typeof RunsRunIdRouteImport;
      parentRoute: typeof RunsRoute;
    };
    "/profile/import": {
      id: "/profile/import";
      path: "/import";
      fullPath: "/profile/import";
      preLoaderRoute: typeof ProfileImportRouteImport;
      parentRoute: typeof ProfileRoute;
    };
    "/jobs/$jobId": {
      id: "/jobs/$jobId";
      path: "/$jobId";
      fullPath: "/jobs/$jobId";
      preLoaderRoute: typeof JobsJobIdRouteImport;
      parentRoute: typeof JobsRoute;
    };
    "/artifacts/$artifactId": {
      id: "/artifacts/$artifactId";
      path: "/$artifactId";
      fullPath: "/artifacts/$artifactId";
      preLoaderRoute: typeof ArtifactsArtifactIdRouteImport;
      parentRoute: typeof ArtifactsRoute;
    };
    "/activity/$eventId": {
      id: "/activity/$eventId";
      path: "/activity/$eventId";
      fullPath: "/activity/$eventId";
      preLoaderRoute: typeof ActivityEventIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile/import/upload": {
      id: "/profile/import/upload";
      path: "/upload";
      fullPath: "/profile/import/upload";
      preLoaderRoute: typeof ProfileImportUploadRouteImport;
      parentRoute: typeof ProfileImportRoute;
    };
    "/profile/import/preview": {
      id: "/profile/import/preview";
      path: "/preview";
      fullPath: "/profile/import/preview";
      preLoaderRoute: typeof ProfileImportPreviewRouteImport;
      parentRoute: typeof ProfileImportRoute;
    };
    "/profile/import/confirm": {
      id: "/profile/import/confirm";
      path: "/confirm";
      fullPath: "/profile/import/confirm";
      preLoaderRoute: typeof ProfileImportConfirmRouteImport;
      parentRoute: typeof ProfileImportRoute;
    };
    "/jobs/$jobId/run/$runId": {
      id: "/jobs/$jobId/run/$runId";
      path: "/run/$runId";
      fullPath: "/jobs/$jobId/run/$runId";
      preLoaderRoute: typeof JobsJobIdRunRunIdRouteImport;
      parentRoute: typeof JobsJobIdRoute;
    };
  }
}

interface ArtifactsRouteChildren {
  ArtifactsArtifactIdRoute: typeof ArtifactsArtifactIdRoute;
  ArtifactsIndexRoute: typeof ArtifactsIndexRoute;
}

const ArtifactsRouteChildren: ArtifactsRouteChildren = {
  ArtifactsArtifactIdRoute: ArtifactsArtifactIdRoute,
  ArtifactsIndexRoute: ArtifactsIndexRoute,
};

const ArtifactsRouteWithChildren = ArtifactsRoute._addFileChildren(
  ArtifactsRouteChildren,
);

interface JobsJobIdRouteChildren {
  JobsJobIdRunRunIdRoute: typeof JobsJobIdRunRunIdRoute;
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdRunRunIdRoute: JobsJobIdRunRunIdRoute,
};

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
);

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren;
  JobsIndexRoute: typeof JobsIndexRoute;
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
  JobsIndexRoute: JobsIndexRoute,
};

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren);

interface ProfileImportRouteChildren {
  ProfileImportConfirmRoute: typeof ProfileImportConfirmRoute;
  ProfileImportPreviewRoute: typeof ProfileImportPreviewRoute;
  ProfileImportUploadRoute: typeof ProfileImportUploadRoute;
}

const ProfileImportRouteChildren: ProfileImportRouteChildren = {
  ProfileImportConfirmRoute: ProfileImportConfirmRoute,
  ProfileImportPreviewRoute: ProfileImportPreviewRoute,
  ProfileImportUploadRoute: ProfileImportUploadRoute,
};

const ProfileImportRouteWithChildren = ProfileImportRoute._addFileChildren(
  ProfileImportRouteChildren,
);

interface ProfileRouteChildren {
  ProfileImportRoute: typeof ProfileImportRouteWithChildren;
  ProfileIndexRoute: typeof ProfileIndexRoute;
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileImportRoute: ProfileImportRouteWithChildren,
  ProfileIndexRoute: ProfileIndexRoute,
};

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren);

interface RunsRouteChildren {
  RunsRunIdRoute: typeof RunsRunIdRoute;
  RunsIndexRoute: typeof RunsIndexRoute;
}

const RunsRouteChildren: RunsRouteChildren = {
  RunsRunIdRoute: RunsRunIdRoute,
  RunsIndexRoute: RunsIndexRoute,
};

const RunsRouteWithChildren = RunsRoute._addFileChildren(RunsRouteChildren);

interface SettingsRouteChildren {
  SettingsCredentialsRoute: typeof SettingsCredentialsRoute;
  SettingsIndexRoute: typeof SettingsIndexRoute;
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCredentialsRoute: SettingsCredentialsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
};

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyReviewRoute: ApplyReviewRoute,
  ArtifactsRoute: ArtifactsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DebugRoute: DebugRoute,
  DiscoveryRoute: DiscoveryRoute,
  JobsRoute: JobsRouteWithChildren,
  PipelinesRoute: PipelinesRoute,
  PreferencesRoute: PreferencesRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RunsRoute: RunsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  ActivityEventIdRoute: ActivityEventIdRoute,
  SpikesTableFiltersRoute: SpikesTableFiltersRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
