import type { DemoCapabilityManifest } from "./contracts.js";

const local = (reason: string) => ({ class: "browser_local", reason }) as const;
const async = (reason: string) => ({ class: "simulated_async", reason }) as const;
const rehearsal = (reason: string) => ({ class: "rehearsed_external", reason }) as const;
const unavailable = (reason: string) => ({ class: "unavailable", reason }) as const;

/**
 * Every port member is deliberately classified before a demo adapter exists.
 * `satisfies` makes a newly added ApiClientPort member a compile-time failure.
 */
export const DEMO_CAPABILITY_MANIFEST = {
  health: local("Shows synthetic browser-local service health."),
  dashboardSummary: local("Reads the synthetic dashboard projection."),
  outcomeAnalytics: local("Reads synthetic conversion analytics."),
  digest: local("Reads the synthetic daily digest."),
  acknowledgeDigest: local("Acknowledges a digest only in browser-local state."),
  activity: local("Reads synthetic activity history."),
  activityEvent: local("Reads a synthetic activity event."),
  discoverySettings: local("Reads synthetic discovery preferences."),
  updateDiscoverySettings: local("Edits synthetic discovery preferences locally."),
  discoverySources: local("Reads synthetic discovery sources."),
  upsertDiscoverySource: local("Edits a synthetic source locally."),
  patchDiscoverySourceState: local("Changes a synthetic source state locally."),
  discoverySourcePreview: rehearsal("Rehearses a lead preview without fetching a site."),
  compensationSources: local("Reads synthetic compensation source policy."),
  updateCompensationSourcePolicy: local("Edits synthetic compensation policy locally."),
  discoveryLocatorCandidates: local("Reads bundled source-locator candidates."),
  promoteSourceLocatorCandidate: local("Promotes a bundled candidate locally."),
  rejectSourceLocatorCandidate: local("Rejects a bundled candidate locally."),
  discoveryQuarantine: local("Reads synthetic quarantine records."),
  decideDiscoveryQuarantine: local("Decides a synthetic quarantine record locally."),
  manualCaptureQueue: local("Reads the bundled browser-capture fixture."),
  importManualCapture: local("Imports a bundled capture fixture locally."),
  dismissManualCapture: local("Dismisses a bundled capture fixture locally."),
  recordDiscoveryFeedback: local("Records feedback only in browser-local state."),
  roleMatchFeedbackSuggestions: local("Reads synthetic role-match feedback."),
  decideRoleMatchFeedbackSuggestion: local("Decides synthetic feedback locally."),
  applyReviewQueue: local("Reads the synthetic review queue."),
  decideApplyReview: local("Records an approval decision locally."),
  resumeReviewDraft: local("Reads a synthetic review draft."),
  createResumeReviewDraft: local("Creates a synthetic draft locally."),
  saveResumeReviewDraftRevision: local("Saves a draft revision locally."),
  seedResumeReviewCommentThreads: local("Seeds synthetic review comments locally."),
  renderResumeReviewDraft: unavailable("Draft rendering is deferred from the public-demo MVP."),
  replyToResumeReviewComment: local("Records a comment reply locally."),
  resumeReviewFeedback: local("Reads synthetic review feedback."),
  resumeTemplates: local("Reads bundled resume templates."),
  resumeTemplate: local("Reads a bundled resume template."),
  saveResumeTemplate: local("Saves a template revision locally."),
  setDefaultResumeTemplate: local("Changes the synthetic default template locally."),
  setJobResumeTemplate: local("Assigns a bundled template locally."),
  ensureCurrentResumeMaterials: unavailable("Material freshness checks are deferred from the public-demo MVP."),
  applicationOutcomes: local("Reads synthetic application outcomes."),
  jobApplicationOutcomes: local("Reads synthetic outcomes for one job."),
  recordManualApplicationOutcome: local("Records a synthetic manual outcome locally."),
  decideOutcomeSuggestion: local("Decides a synthetic outcome suggestion locally."),
  jobs: local("Reads synthetic job projections."),
  job: local("Reads a synthetic job projection."),
  evidenceMap: local("Reads synthetic evidence-map data."),
  deleteJob: local("Soft-deletes a synthetic job locally."),
  deleteJobs: local("Soft-deletes synthetic jobs locally."),
  permanentlyDeleteJob: local("Permanently deletes only browser-local synthetic data."),
  permanentlyDeleteJobs: local("Permanently deletes only browser-local synthetic data."),
  restoreJob: local("Restores a synthetic job locally."),
  restoreJobs: local("Restores synthetic jobs locally."),
  hideJob: local("Hides a synthetic job locally."),
  hideJobs: local("Hides synthetic jobs locally."),
  unhideJob: local("Unhides a synthetic job locally."),
  unhideJobs: local("Unhides synthetic jobs locally."),
  retryFailedJobs: unavailable("Bulk failed-job retry is deferred from the public-demo MVP."),
  runPendingPreparation: unavailable("Bulk pending preparation is deferred from the public-demo MVP."),
  correctScore: local("Corrects a synthetic score locally."),
  resetStaleScoresForRescore: local("Marks synthetic scores stale locally."),
  rescoreJob: async("Simulates a single score run."),
  refreshCompensation: unavailable("Compensation refresh is deferred from the public-demo MVP."),
  refreshAllCompensation: unavailable("Bulk compensation refresh is deferred from the public-demo MVP."),
  rescoreJobsNotOnCurrentScoringPolicy: unavailable("Bulk policy rescoring is deferred from the public-demo MVP."),
  retailorJob: async("Simulates tailoring a job."),
  tailorJob: unavailable("Initial material generation is deferred from the public-demo MVP."),
  retailorCurrentPolicy: unavailable("Bulk policy retailoring is deferred from the public-demo MVP."),
  workflowRuns: local("Reads synthetic workflow runs."),
  workflowRun: local("Reads a synthetic workflow timeline."),
  cancelWorkflowRun: local("Cancels a synthetic pending run locally."),
  artifacts: local("Reads bundled synthetic artifacts."),
  artifact: local("Reads synthetic artifact metadata."),
  artifactPreviewPdfUrl: local("Returns a bundled same-origin PDF URL."),
  artifactPreviewHtmlUrl: local("Returns a bundled same-origin HTML URL."),
  openArtifact: rehearsal("Records an in-browser preview; no host OS opener is invoked."),
  profile: local("Reads the synthetic profile."),
  profilePreviewPdfUrl: local("Returns the bundled synthetic profile PDF."),
  profilePreviewHtmlUrl: local("Returns the bundled synthetic profile HTML."),
  updateProfile: local("Edits only the browser-local synthetic profile."),
  importResume: local("Imports only the bundled sample resume."),
  settings: local("Reads synthetic application settings."),
  updateSettings: local("Edits synthetic settings locally."),
  extensionCapabilityToken: unavailable("Browser-extension pairing is unavailable in the public demo."),
  rotateExtensionCapabilityToken: unavailable("Browser-extension pairing is unavailable in the public demo."),
  runPipelineStages: unavailable("Multi-stage pipeline runs are deferred from the public-demo MVP."),
  credentials: local("Shows a browser-local, read-only explanation with no configured credential values."),
  updateCredential: unavailable("The public demo never reads or accepts credentials."),
  deleteCredential: unavailable("The public demo has no credential store."),
  updateCredentialsBatch: unavailable("The public demo never reads or accepts credentials."),
  providerModels: local("Shows a deterministic, read-only sample model catalog."),
  providerStatus: local("Shows an unconfigured, read-only provider explanation."),
  verifyCodexProvider: unavailable("The public demo cannot inspect host Codex authentication."),
  listContacts: local("Reads synthetic contacts."),
  contact: local("Reads a synthetic contact."),
  createContact: local("Creates a synthetic contact locally."),
  updateContact: local("Edits a synthetic contact locally."),
  deleteContact: local("Deletes a synthetic contact locally."),
  importContacts: unavailable("Bulk contact import is unavailable to avoid personal-data entry."),
  researchTasks: local("Reads synthetic research tasks."),
  researchTask: local("Reads a synthetic research task."),
  runContactResearch: unavailable("Contact research is deferred from the public-demo MVP."),
  confirmContactCandidate: local("Confirms a synthetic candidate locally."),
  outreachThread: local("Reads a synthetic outreach thread."),
  generateOutreachDraft: unavailable("Outreach generation is deferred from the public-demo MVP."),
  reviseOutreachDraft: unavailable("Outreach revision is deferred from the public-demo MVP."),
  approveOutreachDraft: local("Approves a synthetic draft locally."),
  rejectOutreachDraft: local("Rejects a synthetic draft locally."),
  logOutreachSend: unavailable("Send logging is deferred from the public-demo MVP."),
  scheduleOutreachFollowUp: local("Schedules a synthetic follow-up locally."),
  completeOutreachFollowUp: local("Completes a synthetic follow-up locally."),
  dismissOutreachFollowUp: local("Dismisses a synthetic follow-up locally."),
  dueOutreachFollowUps: local("Reads synthetic due follow-ups."),
  retryStage: async("Simulates retrying a pipeline stage."),
  runJobStage: async("Simulates a pipeline stage."),
  generateMaterials: unavailable("Material generation is deferred from the public-demo MVP."),
  generateInterviewPrep: unavailable("Interview-preparation generation is deferred from the public-demo MVP."),
  applyJob: rehearsal("Rehearses a dry-run application and records a receipt."),
  cancelJobAction: local("Cancels a synthetic pending action locally."),
  markApplied: rehearsal("Records a simulated application receipt; nothing is submitted."),
  markSkipped: local("Marks a synthetic job skipped locally."),
} as const satisfies DemoCapabilityManifest;
