import { ProfileSchema } from "@jobctrl/contracts";

import { DEMO_ARTIFACTS } from "./artifacts.js";
import type { DemoReadModel } from "./contracts.js";
import { demoTimestamp } from "./clock.js";

const REFERENCE_TIME = "2026-07-11T09:00:00.000Z";
const REFERENCE_TIME_MS = Date.parse(REFERENCE_TIME);

/** Converts authored fixture moments into clock-relative production seed data. */
const at = (value: string) => demoTimestamp(Math.round((Date.parse(value) - REFERENCE_TIME_MS) / 60_000));

const job = {
  jobKey: "job-northwind-platform",
  url: "demo-job:northwind-platform",
  title: "Platform systems lead",
  company: "Northwind Workshop",
  source: "bundled-capture",
  discoverySource: "demo-source:northwind",
  postingSource: "bundled-capture",
  postingSourceUrl: "/demo/source-preview.html",
  strategy: "demo_rehearsal",
  location: "Distributed",
  salary: "Synthetic range",
  compensationSummary: null,
  discoveredAt: at("2026-07-08T09:00:00.000Z"),
  applicationUrl: "/demo/application-preview.html",
  fitScore: 8,
  scoreBreakdown: {
    technicalFit: 8,
    experienceFit: 8,
    roleFit: 7,
    reasoning: "Synthetic evidence supports the platform-delivery requirements.",
    fitBand: "strong",
    confidence: "high",
    eligibility: { status: "eligible", hardBlockers: [], warnings: [] },
    matchedSignals: ["platform delivery", "reliability practice"],
    missingSignals: ["regulated-domain leadership"],
    transferableSignals: ["incident coordination"],
  },
  scoreKeywords: ["platform", "reliability"],
  scoreReasoning: "Synthetic evidence supports the platform-delivery requirements.",
  scoreVersion: 3,
  scoredAt: at("2026-07-09T09:30:00.000Z"),
  scoreCriteria: {
    minFitScore: 7,
    criteriaText: "Prioritize reliable platform delivery and clear technical leadership.",
    targetCriteria: "Senior platform roles with distributed collaboration.",
    criteriaVersion: "demo-policy-3",
  },
  scoreTrace: {
    promptVersion: "demo-score-contract-1",
    schemaVersion: "demo-score-contract-1",
    model: "simulated",
    criteriaVersion: "demo-policy-3",
    profileSnapshotVersion: 1,
    scoringPolicyId: "demo:scoring-policy-3",
    scoringPolicyVersion: 3,
    rubricVersion: "demo-rubric-1",
    rawWeightedScore: 7.8,
    calibrationAdjustment: 0,
    policyAnchorCount: 1,
    resolvedFitBand: "strong",
    resolutionReason: "deterministic demo score",
    parserWarnings: [],
    correctionHistory: [],
  },
  scoreCorrection: null,
  scoreStaleness: {
    isStale: false,
    staleReason: null,
    currentPolicyVersion: null,
    targetPolicyVersion: null,
    markedAt: null,
    pendingExplicitRescore: false,
  },
  currentStage: "tailor",
  currentSubstage: "tailor",
  currentState: "running",
  errorCode: null,
  errorMessage: null,
  nextAction: null,
  artifactCount: 2,
  applyStatus: null,
  appliedAt: null,
  activeState: "active",
  deletedAt: null,
  hiddenAt: null,
} satisfies DemoReadModel["jobs"]["list"]["items"][number];

const blockedJob = {
  ...job,
  jobKey: "job-contoso-reliability",
  url: "demo-job:contoso-reliability",
  title: "Reliability engineering manager",
  company: "Contoso Workshop",
  fitScore: 4,
  scoreBreakdown: {
    ...job.scoreBreakdown,
    technicalFit: 5,
    experienceFit: 4,
    roleFit: 4,
    fitBand: "stretch",
    confidence: "medium",
    eligibility: { status: "blocked", hardBlockers: ["regulated-domain leadership"], warnings: [] },
    missingSignals: ["regulated-domain leadership"],
  },
  scoreReasoning: "A required domain claim is not present in the synthetic evidence.",
  currentStage: "tailor",
  currentState: "blocked",
  errorCode: "demo_missing_requirement",
  errorMessage: "The demo preserves the explicit requirement gap.",
  nextAction: "Review the missing requirement before tailoring.",
  artifactCount: 2,
} satisfies DemoReadModel["jobs"]["list"]["items"][number];

const staleJob = {
  ...job,
  jobKey: "job-fabrikam-systems",
  url: "demo-job:fabrikam-systems",
  title: "Systems delivery director",
  company: "Fabrikam Workshop",
  fitScore: 7,
  scoreStaleness: {
    isStale: true,
    staleReason: "scoring_policy_changed",
    currentPolicyVersion: 2,
    targetPolicyVersion: 3,
    markedAt: at("2026-07-11T07:00:00.000Z"),
    pendingExplicitRescore: true,
  },
  currentStage: "score",
  currentSubstage: "score",
  currentState: "failed",
  errorCode: "demo_rescore_gate",
  errorMessage: "The synthetic rescore quality gate requested a retry.",
  nextAction: "Retry the rescore against the current synthetic policy.",
  artifactCount: 0,
} satisfies DemoReadModel["jobs"]["list"]["items"][number];

const activity = {
  eventId: "event-demo-score",
  eventType: "JobScored",
  jobKey: job.jobKey,
  title: job.title,
  company: job.company,
  stage: "score",
  level: "info",
  message: "Synthetic score recorded.",
  at: at("2026-07-09T09:30:00.000Z"),
} satisfies DemoReadModel["dashboard"]["summary"]["activity"][number];

const funnel = {
  applied: 3,
  reply: 2,
  interview: 1,
  offer: 1,
  rejection: 1,
  replyRate: 0.67,
  interviewRate: 0.33,
  offerRate: 0.33,
  rejectionRate: 0.33,
  costPerInterview: null,
};

const artifact = {
  artifactId: "artifact-tailored-resume",
  jobKey: job.jobKey,
  title: job.title,
  company: job.company,
  type: "resume_pdf",
  status: "accepted",
  localPath: "/demo/tailored-resume.pdf",
  createdAt: at("2026-07-11T08:00:00.000Z"),
  sizeBytes: 612,
  size: "612 B",
} satisfies DemoReadModel["materials"]["list"]["items"][number];

const textArtifact = {
  artifactId: "artifact-tailored-resume-html",
  jobKey: job.jobKey,
  title: job.title,
  company: job.company,
  type: "tailored_resume",
  status: "accepted",
  localPath: "/demo/tailored-resume.html",
  createdAt: at("2026-07-11T08:00:00.000Z"),
  sizeBytes: 826,
  size: "826 B",
} satisfies DemoReadModel["materials"]["list"]["items"][number];

const contosoResumePdfArtifact = {
  artifactId: "artifact-contoso-resume-pdf-g1",
  jobKey: blockedJob.jobKey,
  title: blockedJob.title,
  company: blockedJob.company,
  type: "resume_pdf",
  status: "accepted",
  localPath: DEMO_ARTIFACTS.tailoredResumePdf.url,
  createdAt: at("2026-07-10T07:00:00.000Z"),
  sizeBytes: 612,
  size: "612 B",
} satisfies DemoReadModel["materials"]["list"]["items"][number];

const contosoResumeTextArtifact = {
  artifactId: "artifact-contoso-resume-g1",
  jobKey: blockedJob.jobKey,
  title: blockedJob.title,
  company: blockedJob.company,
  type: "tailored_resume",
  status: "accepted",
  localPath: DEMO_ARTIFACTS.tailoredResumeHtml.url,
  createdAt: at("2026-07-10T07:00:00.000Z"),
  sizeBytes: 826,
  size: "826 B",
} satisfies DemoReadModel["materials"]["list"]["items"][number];

const applyAudit = {
  state: "ready",
  label: "Materials ready",
  summary: "Bundled materials are ready for a simulated review.",
  reviewEvidenceAvailable: true,
  missingPrerequisites: [],
  hardBlockers: [],
  eligibilityConcerns: [],
  sources: [
    { kind: "materials.resume", label: "Bundled resume", status: "present", detail: "Synthetic artifact is available." },
    { kind: "application_url", label: "Application rehearsal", status: "present", detail: "No live destination is used." },
  ],
} satisfies DemoReadModel["apply"]["queue"]["items"][number]["applyAudit"];

const interviewPrep = {
  jobKey: job.jobKey,
  generation: 1,
  status: "accepted",
  generatedAt: at("2026-07-10T10:00:00.000Z"),
  model: "simulated",
  gateAudit: {
    status: "passed",
    fabricationFindings: [],
    groundingFindings: [],
    judgeVerdict: "grounded",
    warnings: [],
  },
  items: [
    {
      itemId: "prep-reliability-story",
      kind: "star_draft",
      title: "Reliability improvement story",
      generatedText: "Describe the documented reliability improvement and its review trail.",
      evidenceIds: ["evidence-delivery-improvement"],
      requirementIds: ["requirement-platform"],
      sourceText: ["Coordinated a reliability improvement."],
      transformType: "grounded_demo",
      control: "evidence_required",
      groundingAudit: ["Linked to bundled synthetic evidence."],
      warnings: [],
      position: 1,
    },
  ],
} satisfies NonNullable<DemoReadModel["jobs"]["details"][string]["interviewPrep"]>;

const resumeDraft = {
  draftId: "draft-tailored-resume",
  jobKey: job.jobKey,
  baseGeneration: 1,
  baseResumeTextArtifactId: "artifact-tailored-resume-html",
  baseResumePdfArtifactId: artifact.artifactId,
  rendererFormat: "html_pdf",
  state: "rendered",
  currentRevisionId: "revision-tailored-resume-1",
  latestRevisionNumber: 1,
  createdAt: at("2026-07-11T08:00:00.000Z"),
  updatedAt: at("2026-07-11T08:05:00.000Z"),
  latestRevision: {
    revisionId: "revision-tailored-resume-1",
    draftId: "draft-tailored-resume",
    jobKey: job.jobKey,
    revisionNumber: 1,
    editedText: "Bundled synthetic tailored resume.",
    plateDocument: null,
    editDeltas: [],
    createdAt: at("2026-07-11T08:05:00.000Z"),
  },
  commentThreads: [
    {
      threadId: "comment-tailored-resume-1",
      draftId: "draft-tailored-resume",
      jobKey: job.jobKey,
      baseArtifactId: artifact.artifactId,
      semanticId: "experience-synthetic",
      lineAnchor: { semanticId: "experience-synthetic", lineNumber: 4, pageNumber: 1, textHash: "demo-line" },
      sourcePinId: "evidence-delivery-improvement",
      riskLabel: "reviewed",
      commentBody: "Synthetic comment retained for audit review.",
      state: "resolved",
      anchorResolved: true,
      createdAt: at("2026-07-11T08:03:00.000Z"),
      updatedAt: at("2026-07-11T08:05:00.000Z"),
      replies: [],
    },
  ],
  feedbackSignals: [],
} satisfies DemoReadModel["materials"]["resumeReviewDrafts"][string]["draft"];

const templateMetadata = {
  templateId: "demo-template",
  templateVersionId: "demo-template-v1",
  templateVersionNumber: 1,
  templateName: "Bundled demo template",
  templateHash: "demo-template-hash",
  assignmentSource: "built_in",
} satisfies NonNullable<DemoReadModel["materials"]["resumeTemplates"]["defaultTemplate"]>;

const resumeTemplate = {
  templateId: templateMetadata.templateId,
  displayName: templateMetadata.templateName,
  status: "active",
  builtIn: true,
  activeVersion: {
    templateId: templateMetadata.templateId,
    versionId: templateMetadata.templateVersionId,
    versionNumber: 1,
    displayName: templateMetadata.templateName,
    status: "active",
    theme: {
      pageSize: "a4",
      fontFamily: "sans",
      fontScale: 1,
      density: "balanced",
      marginMm: { top: 16, right: 16, bottom: 16, left: 16 },
      headerLayout: "left",
      sectionHeadingStyle: "rule",
      alignment: "left",
      bulletSpacing: "normal",
      accentColor: "#172033",
      sectionOrder: ["summary", "experience", "skills"],
      hiddenSections: [],
    },
    layout: {},
    contentHash: "demo-template-hash",
    createdAt: at("2026-07-01T09:00:00.000Z"),
  },
  createdAt: at("2026-07-01T09:00:00.000Z"),
  updatedAt: at("2026-07-01T09:00:00.000Z"),
} satisfies DemoReadModel["materials"]["resumeTemplates"]["templates"][number];

/**
 * Server-shaped, production-bundle fixture data. P2 can use these exact port
 * responses while its adapter maps the remaining commands onto the workspace.
 */
export const DEMO_READ_MODEL = {
  dashboard: {
    health: {
      ok: true,
      appDir: "browser-local-demo",
      dbPath: "browser-local-demo",
      dbExists: true,
      dbIdentity: "demo-fixture-v1",
      llmSpend: {
        status: "ok",
        day: "2026-07-11",
        inputTokens: 0,
        outputTokens: 0,
        estimatedUsd: 0,
        dailyBudgetUsd: 20,
        remainingUsd: 20,
        unlimited: false,
        message: "The public demo makes no model-provider calls.",
      },
      worker: {
        status: "healthy",
        expectedDbPath: "browser-local-demo",
        expectedAppDir: "browser-local-demo",
        staleAfterSeconds: 180,
        message: "The demo uses a deterministic browser-local scenario.",
        heartbeat: null,
      },
    },
    summary: {
      ok: true,
      generatedAt: at("2026-07-11T09:00:00.000Z"),
      totals: { jobs: 3, jobsToday: 1, failures: 1, blocked: 1, ready: 2, applied: 3, appliedToday: 0, dryRuns: 2 },
      work: {
        active: 2,
        stuck: 0,
        stuckAfterSeconds: 180,
        stuckItems: [],
      },
      preparation: {
        currentScoringPolicyVersion: 3,
        currentTailoringPolicyVersion: 2,
        outdatedScoreCount: 1,
        outdatedTailoredArtifactCount: 1,
        workItems: { queued: 1, running: 1, failed: 1 },
      },
      funnel: [
        { stage: "discover", total: 3, succeeded: 2, running: 0, pending: 0, blocked: 1, failed: 0 },
        { stage: "score", total: 3, succeeded: 1, running: 1, pending: 0, blocked: 0, failed: 1 },
        { stage: "tailor", total: 3, succeeded: 1, running: 1, pending: 0, blocked: 1, failed: 0 },
        { stage: "apply", total: 2, succeeded: 1, running: 0, pending: 1, blocked: 0, failed: 0 },
      ],
      conversion: {
        totals: funnel,
        bySource: [{ source: "bundled-capture", ...funnel }],
        byBand: [{ band: "strong", ...funnel }],
      },
      activity: [activity],
      progress: [
        {
          stage: "tailor",
          status: "running",
          runId: "run-materials-progress",
          workflowId: "run-materials-progress",
          percent: 50,
          completed: 1,
          total: 2,
          currentStep: "Checking grounded claims",
          message: "Synthetic material review is in progress.",
          updatedAt: at("2026-07-11T08:58:00.000Z"),
        },
      ],
      sourceHealth: [
        {
          sourceId: "demo-source:northwind",
          recommendedState: "active",
          runCount: 4,
          failedRunCount: 0,
          consecutiveFailures: 0,
          observedJobs: 3,
          newJobs: 2,
          existingJobs: 4,
          duplicateRate: 0.67,
          activeVerificationRate: 1,
          fullDescriptionSuccessRate: 1,
          applyUrlSuccessRate: 1,
          operationalFailureCount: 0,
          scrapeFailureCount: 0,
          retryableFailureCount: 0,
          lastFailureCategory: null,
          lastRunId: "run-discovery-cancelled",
          lastErrorClass: null,
          politeness: {
            robotsDisallowedCount: 0,
            rateLimitedCount: 0,
            budgetExhaustedCount: 0,
            lastBlockedReason: null,
            lastBlockedAt: null,
          },
          updatedAt: at("2026-07-11T08:30:00.000Z"),
        },
      ],
      operationalMetrics: {
        attempts: 8,
        failures: 1,
        operationalFailures: 0,
        scrapeFailures: 0,
        retryableFailures: 1,
        byStage: [],
        bySource: [],
      },
      applyRuns: [
        {
          runId: "run-application-rehearsal",
          jobKey: job.jobKey,
          title: job.title,
          company: job.company,
          status: "dry_run_complete",
          dryRun: true,
          startedAt: at("2026-07-11T08:30:00.000Z"),
          events: [
            { at: at("2026-07-11T08:31:00.000Z"), type: "dry_run", level: "info", message: "No application submitted." },
          ],
        },
      ],
    },
    digest: {
      ok: true,
      generatedAt: at("2026-07-11T09:00:00.000Z"),
      since: at("2026-07-04T00:00:00.000Z"),
      highFitThreshold: 7,
      newMatches: { count: 2, highFitCount: 1 },
      blockedSources: { count: 1, sources: [{ sourceId: "demo-source:review", recommendedState: "quarantined", consecutiveFailures: 1 }] },
      reviewNeededMaterials: { count: 1 },
      staleScores: { count: 1 },
      pendingApprovals: { count: 1 },
      followUpsDue: { count: 1, derived: true, thresholdDays: 7, dayBoundary: "UTC" },
      budget: { status: "ok", estimatedUsd: 0, dailyBudgetUsd: 20, remainingUsd: 20, unlimited: false },
      deepLinks: {
        newMatches: "/jobs",
        blockedSources: "/discovery",
        reviewNeededMaterials: "/apply-review",
        staleScores: "/jobs",
        pendingApprovals: "/apply-review",
        followUpsDue: "/outreach",
        budget: "/settings",
      },
    },
    activity: {
      ok: true,
      items: [activity],
      pagination: { page: 1, pageSize: 50, total: 1, pages: 1 },
      sort: { field: "at", dir: "desc" },
      filter: {},
    },
    activityEvents: {
      [activity.eventId]: { ok: true, event: activity },
    },
  },
  jobs: {
    list: {
      ok: true,
      items: [job, blockedJob, staleJob],
      pagination: { page: 1, pageSize: 50, total: 3, pages: 1 },
      sort: { field: "discovered_at", dir: "desc" },
      filter: {},
    },
    details: {
      [job.jobKey]: {
        ok: true,
        job: { ...job, descriptionPreview: "Bundled synthetic role description for a platform systems lead." },
        applyAudit,
        stages: [
          {
            stage: "tailor",
            state: "running",
            attemptCount: 1,
            maxAttempts: 3,
            startedAt: at("2026-07-11T08:57:00.000Z"),
            updatedAt: at("2026-07-11T08:58:00.000Z"),
            finishedAt: null,
            durationMs: null,
            errorCode: null,
            errorMessage: null,
            retryable: true,
            blockedBy: [],
            nextAction: "Review deterministic materials progress.",
          },
        ],
        artifacts: [artifact, textArtifact],
        auditHistory: [
          {
            id: "audit-score",
            category: "scoring",
            tone: "success",
            title: "Synthetic score recorded",
            description: "The seeded score is grounded in bundled evidence.",
            occurredAt: at("2026-07-09T09:30:00.000Z"),
            actor: "demo",
            details: [{ label: "Score", value: "8" }],
          },
        ],
        employerAnalysis: null,
        requirementFitReport: null,
        interviewPrep,
        compensationAudit: null,
      },
      [blockedJob.jobKey]: {
        ok: true,
        job: { ...blockedJob, descriptionPreview: "Synthetic role with an intentionally visible hard requirement gap." },
        applyAudit: {
          state: "blocked",
          label: "Requirement gap",
          summary: "Tailoring cannot invent the missing regulated-domain claim.",
          reviewEvidenceAvailable: true,
          missingPrerequisites: [
            {
              code: "missing_requirement",
              label: "Regulated-domain leadership",
              detail: "No bundled evidence supports this claim.",
              severity: "blocking",
              source: "demo_requirement_fit",
            },
          ],
          hardBlockers: [
            {
              code: "missing_requirement",
              label: "Regulated-domain leadership",
              detail: "No bundled evidence supports this claim.",
              severity: "blocking",
              source: "demo_requirement_fit",
            },
          ],
          eligibilityConcerns: [],
          sources: [
            {
              kind: "materials.resume",
              label: "Accepted resume text",
              status: "present",
              detail: "Generation 1 remains reviewable while replacement tailoring is blocked.",
            },
            {
              kind: "materials.resume_pdf",
              label: "Accepted resume PDF",
              status: "present",
              detail: "Generation 1 remains previewable from the bundled demo asset.",
            },
          ],
        },
        stages: [
          {
            stage: "tailor",
            state: "blocked",
            attemptCount: 1,
            maxAttempts: 1,
            startedAt: at("2026-07-11T07:30:00.000Z"),
            updatedAt: at("2026-07-11T07:31:00.000Z"),
            finishedAt: at("2026-07-11T07:31:00.000Z"),
            durationMs: 60_000,
            errorCode: "demo_missing_requirement",
            errorMessage: "Synthetic gap is preserved.",
            retryable: false,
            blockedBy: ["regulated-domain leadership"],
            nextAction: "Review the explicit gap.",
          },
        ],
        artifacts: [contosoResumeTextArtifact, contosoResumePdfArtifact],
        auditHistory: [],
        employerAnalysis: null,
        requirementFitReport: null,
        interviewPrep: null,
        compensationAudit: null,
      },
      [staleJob.jobKey]: {
        ok: true,
        job: { ...staleJob, descriptionPreview: "Synthetic role retained to demonstrate a stale scoring policy." },
        applyAudit: {
          state: "repair",
          label: "Score policy changed",
          summary: "The score remains inspectable until an explicit refresh succeeds.",
          reviewEvidenceAvailable: true,
          missingPrerequisites: [],
          hardBlockers: [],
          eligibilityConcerns: [],
          sources: [],
        },
        stages: [
          {
            stage: "score",
            state: "failed",
            attemptCount: 2,
            maxAttempts: 2,
            startedAt: at("2026-07-11T08:20:00.000Z"),
            updatedAt: at("2026-07-11T08:22:00.000Z"),
            finishedAt: at("2026-07-11T08:22:00.000Z"),
            durationMs: 120_000,
            errorCode: "demo_rescore_gate",
            errorMessage: "The synthetic rescore quality gate requested a retry.",
            retryable: true,
            blockedBy: [],
            nextAction: "Retry the rescore with the current policy.",
          },
        ],
        artifacts: [],
        auditHistory: [],
        employerAnalysis: null,
        requirementFitReport: null,
        interviewPrep: null,
        compensationAudit: null,
      },
    },
  },
  discovery: {
    settings: {
      ok: true,
      settings: {
        boards: ["indeed", "linkedin"],
        resultsPerSite: 12,
        hoursOld: 72,
        schedulingEnabled: false,
        scheduleCron: "0 9 * * 1",
        roleFilterMode: "auto",
        roleFilterModel: null,
        maxParallelFamilies: 1,
        crawlUserAgentProduct: "JobCtrl",
        crawlUserAgentContact: "https://github.com/ebarti/JobCtrl",
        source: "database",
      },
      effectiveSettings: {
        boards: { value: ["indeed", "linkedin"], source: "persisted", activation: "next_run", editable: true },
        resultsPerSite: { value: 12, source: "persisted", activation: "next_run", editable: true },
        hoursOld: { value: 72, source: "persisted", activation: "next_run", editable: true },
        schedulingEnabled: { value: false, source: "persisted", activation: "restart", editable: true },
        scheduleCron: { value: "0 9 * * 1", source: "persisted", activation: "restart", editable: true },
        roleFilterMode: { value: "auto", source: "default", activation: "next_source_family", editable: true },
        roleFilterModel: { value: null, source: "default", activation: "next_source_family", editable: true },
        maxParallelFamilies: { value: 1, source: "default", activation: "next_run", editable: true },
        crawlUserAgentProduct: { value: "JobCtrl", source: "default", activation: "next_source_family", editable: true },
        crawlUserAgentContact: { value: "https://github.com/ebarti/JobCtrl", source: "default", activation: "next_source_family", editable: true },
      },
    },
    sources: {
      ok: true,
      sources: [
        {
          sourceId: "demo-source:northwind",
          kind: "user_mediated_capture",
          displayName: "Bundled synthetic source",
          owner: "system",
          priority: "standard",
          state: "active",
          policyId: "demo-source-policy",
          recommendedState: "normal",
          lastRunId: "run-discovery-demo",
          lastRunCompletedAt: at("2026-07-11T08:30:00.000Z"),
          lastErrorClass: null,
          consecutiveFailures: 0,
          observedJobs: 3,
          newJobs: 2,
          duplicateRate: 0.67,
          activeVerificationRate: 1,
          fullDescriptionSuccessRate: 1,
          applyUrlSuccessRate: 1,
          politeness: {
            robotsDisallowedCount: 0,
            rateLimitedCount: 0,
            budgetExhaustedCount: 0,
            lastBlockedReason: null,
            lastBlockedAt: null,
          },
          qualityTrend: "flat",
        },
        {
          sourceId: "demo-source:review",
          kind: "user_mediated_capture",
          displayName: "Bundled review source",
          owner: "system",
          priority: "fallback",
          state: "quarantined",
          policyId: "demo-source-review-policy",
          recommendedState: "quarantined",
          lastRunId: "run-discovery-cancelled",
          lastRunCompletedAt: at("2026-07-11T08:02:00.000Z"),
          lastErrorClass: null,
          consecutiveFailures: 1,
          observedJobs: 1,
          newJobs: 1,
          duplicateRate: 0,
          activeVerificationRate: 0,
          fullDescriptionSuccessRate: 0,
          applyUrlSuccessRate: 0,
          politeness: {
            robotsDisallowedCount: 0,
            rateLimitedCount: 0,
            budgetExhaustedCount: 0,
            lastBlockedReason: null,
            lastBlockedAt: null,
          },
          qualityTrend: "down",
        },
      ],
    },
    sourcePreviews: {
      "demo-source:northwind": {
        ok: true,
        sourceId: "demo-source:northwind",
        leads: [
          {
            candidateUrl: "/demo/source-preview.html",
            title: job.title,
            company: job.company,
            location: job.location,
            estimatedConfidence: 1,
          },
        ],
        generatedAt: at("2026-07-11T08:30:00.000Z"),
      },
      "demo-source:review": {
        ok: true,
        sourceId: "demo-source:review",
        leads: [],
        generatedAt: at("2026-07-11T08:02:00.000Z"),
      },
    },
    compensationSources: {
      ok: true,
      sources: [
        {
          sourceId: "demo-posted-salary",
          displayName: "Bundled posting text",
          sourceType: "posted_salary",
          accessMode: "local_posting_text",
          availability: "available",
          licenseStatus: "not_required",
          termsUrl: null,
          sourceUrl: null,
          freshnessPolicy: "Bundled with the demo fixture.",
          attributionRequirement: "Show the bundled-source label.",
          supportedFields: ["posted_range"],
          disabledReason: null,
          configured: true,
          control: { kind: "fixed", enabled: true },
          coverage: { geography: "Synthetic", regions: [], notes: "No provider is queried." },
          notes: ["Static demo data only."],
        },
      ],
    },
    locatorCandidates: {
      ok: true,
      candidates: [
        {
          candidateId: "locator-demo-northwind",
          candidateUrl: "/demo/source-preview.html",
          sourceKind: "user_mediated_capture",
          confidence: 1,
          detectedAtsKind: "bundled_fixture",
          employerDomainMatched: false,
          manualActionReason: "browser_extension_capture",
          discoveredAt: at("2026-07-11T08:10:00.000Z"),
        },
      ],
    },
    quarantine: {
      ok: true,
      entries: [
        {
          jobId: "job-quarantine-demo",
          jobKey: "job-quarantine-demo",
          title: "Uncertain synthetic opportunity",
          company: "Sample workshop",
          sourceId: "demo-source:review",
          postingUrl: "/demo/source-preview.html",
          reason: "user_review_requested",
          confidence: 0.5,
          snapshotVersion: 1,
          capturedAt: at("2026-07-11T08:00:00.000Z"),
          noticeText: "Review this synthetic capture before accepting it.",
        },
      ],
    },
    manualCapture: {
      ok: true,
      items: [
        {
          itemId: "capture-demo-browser",
          originatingUrl: "https://demo.invalid/source-preview.html",
          sourceId: "demo-source:northwind",
          reason: "browser_extension_capture",
          retryContext: { simulated: true },
          requiredAt: at("2026-07-11T08:10:00.000Z"),
          status: "pending",
        },
      ],
    },
    roleMatchFeedback: {
      ok: true,
      suggestions: [
        {
          suggestionId: "role-feedback-demo",
          status: "pending",
          ruleKind: "exact_title_exclusion",
          titlePattern: "Synthetic operations role",
          titleDisplay: "Synthetic operations role",
          reasonCode: "role_mismatch_evidence",
          reason: "The bundled evidence demonstrates a reviewable mismatch decision.",
          sampleCount: 1,
          sourceIds: ["demo-source:northwind"],
          evidence: [
            {
              jobKey: job.jobKey,
              title: job.title,
              company: job.company,
              sourceId: "demo-source:northwind",
              fitScore: job.fitScore,
              roleFit: job.scoreBreakdown.roleFit,
              reason: "Synthetic role-fit review.",
              scoredAt: job.scoredAt,
            },
          ],
          createdAt: at("2026-07-11T08:15:00.000Z"),
          updatedAt: at("2026-07-11T08:15:00.000Z"),
          decidedAt: null,
          decisionReason: null,
        },
      ],
    },
  },
  evidence: {
    ok: true,
    entries: [
      {
        entryId: "evidence-delivery-improvement",
        kind: "achievement_evidence",
        evidenceId: "evidence-delivery-improvement",
        skillId: null,
        title: "Delivery improvement evidence",
        story: {
          scope: "Platform delivery",
          action: "Coordinated a reliability improvement.",
          outcome: "Made the operating path easier to review.",
          metrics: ["synthetic demonstration"],
        },
        skills: ["platform delivery", "reliability"],
        tags: ["grounded", "synthetic"],
        freshness: {
          evidenceDateRange: "Synthetic timeline",
          evidenceStrength: "verified",
          userConfirmed: true,
          claimConfidence: 0.9,
          lastUsedAt: at("2026-07-09T09:30:00.000Z"),
        },
        resumeUsages: [],
        requirementUsages: [
          {
            kind: "requirement_fit",
            jobKey: job.jobKey,
            jobTitle: job.title,
            employer: job.company,
            artifactId: "artifact-tailored-resume",
            bulletId: null,
            generation: 1,
            generatedTextPreview: "Coordinated a reliability improvement.",
            scoreVersion: 3,
            requirementId: "requirement-platform",
            requirementText: "Guide reliable platform delivery.",
            requirementFitKind: "matched",
            artifactCoverageState: "covered",
            keyword: "reliability",
            coverageState: "covered",
            occurredAt: at("2026-07-09T09:30:00.000Z"),
          },
        ],
        coverageUsages: [],
        gaps: [],
      },
    ],
    gaps: [
      {
        gapId: "gap-regulated-domain",
        kind: "missing_requirement",
        requirementId: "requirement-regulated-domain",
        requirementText: "Lead in a regulated domain.",
        demandedSkill: "regulated delivery",
        tier: "must_have",
        weight: 0.8,
        fitKind: "missing",
        reason: "No synthetic evidence supports this claim.",
        jobRefs: [],
      },
    ],
    generatedAt: at("2026-07-11T09:00:00.000Z"),
  },
  materials: {
    list: {
      ok: true,
      items: [
        artifact,
        textArtifact,
        contosoResumeTextArtifact,
        contosoResumePdfArtifact,
      ],
      pagination: { page: 1, pageSize: 50, total: 4, pages: 1 },
      sort: { field: "created_at", dir: "desc" },
      filter: {},
    },
    details: {
      [artifact.artifactId]: {
        ok: true,
        artifact,
        layoutBoxes: [
          {
            semanticId: "experience-synthetic",
            pageNumber: 1,
            lineNumber: 4,
            textExcerpt: "Coordinated a reliability improvement.",
            leftPct: 12,
            topPct: 35,
            widthPct: 76,
            heightPct: 5,
          },
        ],
        tailoringExplanation: null,
      },
      [textArtifact.artifactId]: {
        ok: true,
        artifact: textArtifact,
        layoutBoxes: [],
        tailoringExplanation: null,
      },
      [contosoResumeTextArtifact.artifactId]: {
        ok: true,
        artifact: contosoResumeTextArtifact,
        layoutBoxes: [],
        tailoringExplanation: null,
      },
      [contosoResumePdfArtifact.artifactId]: {
        ok: true,
        artifact: contosoResumePdfArtifact,
        layoutBoxes: [
          {
            semanticId: "requirement-gap-preserved",
            pageNumber: 1,
            lineNumber: 4,
            textExcerpt: "No unsupported regulated-domain claim is added.",
            leftPct: 12,
            topPct: 35,
            widthPct: 76,
            heightPct: 5,
          },
        ],
        tailoringExplanation: null,
      },
    },
    resumeReviewDrafts: {
      [job.jobKey]: { ok: true, draft: resumeDraft },
    },
    resumeReviewFeedback: {
      [job.jobKey]: { ok: true, jobKey: job.jobKey, feedbackSignals: [] },
    },
    resumeTemplates: {
      ok: true,
      templates: [resumeTemplate],
      defaultTemplate: templateMetadata,
      builtInDefault: templateMetadata,
    },
    templateDetails: {
      [resumeTemplate.templateId]: { ok: true, template: resumeTemplate },
    },
  },
  apply: {
    queue: {
      ok: true,
      items: [
        {
          jobKey: job.jobKey,
          title: job.title,
          company: job.company,
          source: job.source,
          compensationSummary: null,
          fitScore: job.fitScore,
          scoreBreakdown: job.scoreBreakdown,
          scoreKeywords: job.scoreKeywords,
          scoreReasoning: job.scoreReasoning,
          scoreVersion: job.scoreVersion,
          scoredAt: job.scoredAt,
          scoreCriteria: job.scoreCriteria,
          scoreTrace: job.scoreTrace,
          applicationUrl: job.applicationUrl,
          currentStage: "apply",
          currentState: "pending",
          materials: { hasResume: true, hasCoverLetter: true, hasPdf: true, ready: true },
          applyAudit,
          position: {
            descriptionPreview: "Bundled synthetic role description.",
            idealCandidate: "A grounded platform-delivery leader.",
            idealRequirements: [],
            requirements: ["platform delivery"],
            matched: ["platform delivery"],
            missing: [],
            transferable: ["incident coordination"],
            keywords: ["platform", "reliability"],
          },
          materialsPreview: {
            materialsGeneration: 1,
            resumeText: "Bundled synthetic tailored resume.",
            resumeTextArtifactId: "artifact-tailored-resume-html",
            resumePdfArtifactId: artifact.artifactId,
            resumePdfLayoutBoxes: [],
            profileSourceFields: [],
            coverLetterText: "Bundled synthetic cover-letter preview.",
          },
          latestApplyRun: {
            runId: "run-application-rehearsal",
            status: "dry_run_complete",
            result: "dry_run",
            dryRun: true,
            startedAt: at("2026-07-11T08:30:00.000Z"),
            finishedAt: at("2026-07-11T08:31:00.000Z"),
          },
          emailApplication: null,
          review: { state: "pending", decision: null, decidedAt: null },
          approvalGate: {
            materialsGeneration: 1,
            profileVersion: 1,
            applicationUrl: job.applicationUrl,
            dryRunEvidence: {
              runId: "run-application-rehearsal",
              coverage: "full",
              finishedAt: at("2026-07-11T08:31:00.000Z"),
              blockedChannels: [],
            },
            partialDryRunEvidence: null,
            reasons: ["awaiting_approval"],
          },
          blockers: [],
        },
      ],
    },
  },
  runs: {
    list: {
      ok: true,
      items: [
        {
          workflowId: "run-materials-progress",
          runId: "run-materials-progress",
          workflowType: "JobPipelineWorkflow",
          jobKey: job.jobKey,
          title: job.title,
          company: job.company,
          status: "in_progress",
          result: null,
          dryRun: false,
          model: "simulated",
          startedAt: at("2026-07-11T08:57:00.000Z"),
          finishedAt: null,
          durationMs: null,
        },
        {
          workflowId: "run-failed-quality-gate",
          runId: "run-failed-quality-gate",
          workflowType: "JobPipelineWorkflow",
          jobKey: staleJob.jobKey,
          title: staleJob.title,
          company: staleJob.company,
          status: "failed",
          result: null,
          dryRun: false,
          model: "simulated",
          startedAt: at("2026-07-11T08:20:00.000Z"),
          finishedAt: at("2026-07-11T08:22:00.000Z"),
          durationMs: 120_000,
        },
        {
          workflowId: "run-score-succeeded",
          runId: "run-score-succeeded",
          workflowType: "JobPipelineWorkflow",
          jobKey: staleJob.jobKey,
          title: staleJob.title,
          company: staleJob.company,
          status: "succeeded",
          result: "scored",
          dryRun: true,
          model: "simulated",
          startedAt: at("2026-07-10T07:30:00.000Z"),
          finishedAt: at("2026-07-10T07:31:00.000Z"),
          durationMs: 60_000,
        },
        {
          workflowId: "run-application-rehearsal",
          runId: "run-application-rehearsal",
          workflowType: "ApplyWorkflow",
          jobKey: job.jobKey,
          title: job.title,
          company: job.company,
          status: "succeeded",
          result: "dry_run",
          dryRun: true,
          model: "simulated",
          startedAt: at("2026-07-11T08:30:00.000Z"),
          finishedAt: at("2026-07-11T08:31:00.000Z"),
          durationMs: 60_000,
        },
        {
          workflowId: "run-discovery-cancelled",
          runId: "run-discovery-cancelled",
          workflowType: "JobPipelineWorkflow",
          jobKey: job.jobKey,
          title: job.title,
          company: job.company,
          status: "canceled",
          result: null,
          dryRun: true,
          model: null,
          startedAt: at("2026-07-11T08:00:00.000Z"),
          finishedAt: at("2026-07-11T08:02:00.000Z"),
          durationMs: 120_000,
        },
        {
          workflowId: "run-discovery-demo",
          runId: "run-discovery-demo",
          workflowType: "JobPipelineWorkflow",
          jobKey: job.jobKey,
          title: job.title,
          company: job.company,
          status: "succeeded",
          result: "discovered",
          dryRun: true,
          model: null,
          startedAt: at("2026-07-11T08:28:00.000Z"),
          finishedAt: at("2026-07-11T08:30:00.000Z"),
          durationMs: 120_000,
        },
      ],
      pagination: { page: 1, pageSize: 50, total: 6, pages: 1 },
      sort: { field: "started_at", dir: "desc" },
      filter: { status: "all" },
    },
    details: {
      "run-materials-progress": {
        workflowId: "run-materials-progress",
        runId: "run-materials-progress",
        workflowType: "JobPipelineWorkflow",
        status: "in_progress",
        jobKey: job.jobKey,
        title: job.title,
        company: job.company,
        dryRun: false,
        model: "simulated",
        result: null,
        errorCode: null,
        errorMessage: null,
        retryable: true,
        inputSummary: { simulated: true, operation: "tailor" },
        temporalRunId: null,
        startedAt: at("2026-07-11T08:57:00.000Z"),
        finishedAt: null,
        durationMs: null,
        events: [
          { eventType: "WorkflowStarted", occurredAt: at("2026-07-11T08:57:00.000Z"), status: "in_progress", message: "Synthetic run started." },
        ],
      },
      "run-failed-quality-gate": {
        workflowId: "run-failed-quality-gate",
        runId: "run-failed-quality-gate",
        workflowType: "JobPipelineWorkflow",
        status: "failed",
        jobKey: staleJob.jobKey,
        title: staleJob.title,
        company: staleJob.company,
        dryRun: false,
        model: "simulated",
        result: null,
        errorCode: "demo_rescore_gate",
        errorMessage: "The synthetic rescore quality gate requested a retry.",
        retryable: true,
        inputSummary: { simulated: true, operation: "rescoreJob" },
        temporalRunId: null,
        startedAt: at("2026-07-11T08:20:00.000Z"),
        finishedAt: at("2026-07-11T08:22:00.000Z"),
        durationMs: 120_000,
        events: [
          { eventType: "WorkflowStarted", occurredAt: at("2026-07-11T08:20:00.000Z"), status: "in_progress", message: "Synthetic run started." },
          { eventType: "WorkflowFailed", occurredAt: at("2026-07-11T08:22:00.000Z"), status: "failed", message: "Retry is available." },
        ],
      },
      "run-score-succeeded": {
        workflowId: "run-score-succeeded",
        runId: "run-score-succeeded",
        workflowType: "JobPipelineWorkflow",
        status: "succeeded",
        jobKey: staleJob.jobKey,
        title: staleJob.title,
        company: staleJob.company,
        dryRun: true,
        model: "simulated",
        result: "scored",
        errorCode: null,
        errorMessage: null,
        retryable: false,
        inputSummary: { simulated: true, operation: "rescoreJob" },
        temporalRunId: null,
        startedAt: at("2026-07-10T07:30:00.000Z"),
        finishedAt: at("2026-07-10T07:31:00.000Z"),
        durationMs: 60_000,
        events: [
          { eventType: "WorkflowStarted", occurredAt: at("2026-07-10T07:30:00.000Z"), status: "in_progress", message: "Synthetic run started." },
          { eventType: "WorkflowCompleted", occurredAt: at("2026-07-10T07:31:00.000Z"), status: "succeeded", message: "Synthetic score completed." },
        ],
      },
      "run-application-rehearsal": {
        workflowId: "run-application-rehearsal",
        runId: "run-application-rehearsal",
        workflowType: "ApplyWorkflow",
        status: "succeeded",
        jobKey: job.jobKey,
        title: job.title,
        company: job.company,
        dryRun: true,
        model: "simulated",
        result: "dry_run",
        errorCode: null,
        errorMessage: null,
        retryable: false,
        inputSummary: { simulated: true, operation: "applyJob" },
        temporalRunId: null,
        startedAt: at("2026-07-11T08:30:00.000Z"),
        finishedAt: at("2026-07-11T08:31:00.000Z"),
        durationMs: 60_000,
        events: [
          { eventType: "WorkflowStarted", occurredAt: at("2026-07-11T08:30:00.000Z"), status: "in_progress", message: "Dry-run rehearsal started." },
          { eventType: "WorkflowCompleted", occurredAt: at("2026-07-11T08:31:00.000Z"), status: "succeeded", message: "No application was submitted." },
        ],
      },
      "run-discovery-cancelled": {
        workflowId: "run-discovery-cancelled",
        runId: "run-discovery-cancelled",
        workflowType: "JobPipelineWorkflow",
        status: "canceled",
        jobKey: job.jobKey,
        title: job.title,
        company: job.company,
        dryRun: true,
        model: null,
        result: null,
        errorCode: null,
        errorMessage: null,
        retryable: false,
        inputSummary: { simulated: true, operation: "runPipelineStages" },
        temporalRunId: null,
        startedAt: at("2026-07-11T08:00:00.000Z"),
        finishedAt: at("2026-07-11T08:02:00.000Z"),
        durationMs: 120_000,
        events: [
          { eventType: "WorkflowStarted", occurredAt: at("2026-07-11T08:00:00.000Z"), status: "in_progress", message: "Synthetic discovery started." },
          { eventType: "WorkflowCancelled", occurredAt: at("2026-07-11T08:02:00.000Z"), status: "canceled", message: "Synthetic discovery cancelled." },
        ],
      },
      "run-discovery-demo": {
        workflowId: "run-discovery-demo",
        runId: "run-discovery-demo",
        workflowType: "JobPipelineWorkflow",
        status: "succeeded",
        jobKey: job.jobKey,
        title: job.title,
        company: job.company,
        dryRun: true,
        model: null,
        result: "discovered",
        errorCode: null,
        errorMessage: null,
        retryable: false,
        inputSummary: { simulated: true, operation: "runPipelineStages" },
        temporalRunId: null,
        startedAt: at("2026-07-11T08:28:00.000Z"),
        finishedAt: at("2026-07-11T08:30:00.000Z"),
        durationMs: 120_000,
        events: [
          { eventType: "WorkflowStarted", occurredAt: at("2026-07-11T08:28:00.000Z"), status: "in_progress", message: "Synthetic discovery started." },
          { eventType: "WorkflowCompleted", occurredAt: at("2026-07-11T08:30:00.000Z"), status: "succeeded", message: "Synthetic discovery completed." },
        ],
      },
    },
  },
  analytics: {
    summary: {
      ok: true,
      generatedAt: at("2026-07-11T09:00:00.000Z"),
      minSample: 1,
      totals: { n: 3, ...funnel },
      bySource: [{ source: "bundled-capture", n: 3, ...funnel }],
      byScoreBand: [{ scoreBand: "strong", n: 3, ...funnel }],
      byFitBand: [{ fitBand: "strong", n: 3, ...funnel }],
      byApplyMode: [{ applyMode: "manual_marked", n: 3, ...funnel }],
      byTemplate: [{ templateId: "demo-template", templateName: "Bundled demo", n: 3, ...funnel }],
      byPolicy: [{ tailoringPolicyVersion: 2, policyLabel: "Demo policy", n: 3, ...funnel }],
      timeToResponse: { n: 3, medianMinutes: 960 },
      suggestionAccuracy: { n: 2, decided: 2, accepted: 1, corrected: 1, ignored: 0, acceptanceRate: 0.5 },
    },
    outcomes: {
      ok: true,
      outcomes: [
        {
          outcomeId: "outcome-demo-interview",
          jobKey: job.jobKey,
          kind: "interview",
          source: "manual",
          note: "Synthetic interview outcome.",
          occurredAt: at("2026-07-07T12:00:00.000Z"),
          recordedAt: at("2026-07-07T12:01:00.000Z"),
          suggestionId: null,
          evidenceId: null,
          interviewPrepGeneration: 1,
        },
        {
          outcomeId: "outcome-demo-rejection",
          jobKey: "job-contoso-reliability",
          kind: "rejection",
          source: "manual",
          note: "Synthetic rejection outcome.",
          occurredAt: at("2026-07-06T12:00:00.000Z"),
          recordedAt: at("2026-07-06T12:01:00.000Z"),
          suggestionId: null,
          evidenceId: null,
          interviewPrepGeneration: null,
        },
        {
          outcomeId: "outcome-demo-offer",
          jobKey: "job-fabrikam-systems",
          kind: "offer",
          source: "manual",
          note: "Synthetic offer outcome.",
          occurredAt: at("2026-07-05T12:00:00.000Z"),
          recordedAt: at("2026-07-05T12:01:00.000Z"),
          suggestionId: null,
          evidenceId: null,
          interviewPrepGeneration: null,
        },
      ],
      suggestions: [],
    },
    jobOutcomes: {
      [job.jobKey]: {
        ok: true,
        jobKey: job.jobKey,
        outcomes: [
          {
            outcomeId: "outcome-demo-interview",
            jobKey: job.jobKey,
            kind: "interview",
            source: "manual",
            note: "Synthetic interview outcome.",
            occurredAt: at("2026-07-07T12:00:00.000Z"),
            recordedAt: at("2026-07-07T12:01:00.000Z"),
            suggestionId: null,
            evidenceId: null,
            interviewPrepGeneration: 1,
          },
        ],
        suggestions: [],
      },
      [blockedJob.jobKey]: {
        ok: true,
        jobKey: blockedJob.jobKey,
        outcomes: [
          {
            outcomeId: "outcome-demo-rejection",
            jobKey: blockedJob.jobKey,
            kind: "rejection",
            source: "manual",
            note: "Synthetic rejection outcome.",
            occurredAt: at("2026-07-06T12:00:00.000Z"),
            recordedAt: at("2026-07-06T12:01:00.000Z"),
            suggestionId: null,
            evidenceId: null,
            interviewPrepGeneration: null,
          },
        ],
        suggestions: [],
      },
      [staleJob.jobKey]: {
        ok: true,
        jobKey: staleJob.jobKey,
        outcomes: [
          {
            outcomeId: "outcome-demo-offer",
            jobKey: staleJob.jobKey,
            kind: "offer",
            source: "manual",
            note: "Synthetic offer outcome.",
            occurredAt: at("2026-07-05T12:00:00.000Z"),
            recordedAt: at("2026-07-05T12:01:00.000Z"),
            suggestionId: null,
            evidenceId: null,
            interviewPrepGeneration: null,
          },
        ],
        suggestions: [],
      },
    },
  },
  profile: {
    config: {
      ok: true,
      // ProfileConfigResponse.profile intentionally remains `unknown` on the
      // wire. Parse this authored fixture now, then assert it again in the demo
      // invariant so malformed future edits cannot reach the adapter.
      profile: ProfileSchema.parse({
        personal: { full_name: "Synthetic profile" },
        resume: {
          experience_entries: [
            {
              id: "experience-platform-delivery",
              title: "Platform delivery lead",
              company: "Sample workshop",
              bullets: ["Coordinated a reliability improvement."],
            },
          ],
        },
      }),
      style: { family: "sans" },
      templateText: "Bundled demo template",
    },
    credentials: {
      ok: true,
      store: {
        kind: "macos_keychain",
        available: false,
        unavailableReason: "unsupported_platform",
        requiresWorkerRestart: true,
      },
      credentials: [
        { key: "OPENAI_API_KEY", label: "OpenAI API Key", configured: null, storage: "keychain", effectiveSource: "inspection_unknown", editable: false },
        { key: "GEMINI_API_KEY", label: "Gemini API Key", configured: null, storage: "keychain", effectiveSource: "inspection_unknown", editable: false },
      ],
    },
  },
  settings: {
    ok: true,
    settings: {
      targetRole: "Platform systems lead",
      locationFilter: "Distributed",
      minFitScore: 7,
      autoApply: false,
      applyApprovalRequired: true,
      applyConcurrency: 1,
      workerActivitySlots: 4,
      dailyBudgetUsd: 20,
      analysisLegs: ["claude", "codex", "google"],
      tailoringGeneratorModels: null,
      tailoringJudgeModel: null,
      tailoringJudgeMinScore: 0.82,
      applyMaxBudgetUsd: 5,
      applyTimeoutSeconds: 900,
      scoreCriteria: "Synthetic demonstration criteria.",
      targetCriteria: "Synthetic demonstration target.",
      preferredModels: { claude: "sonnet" },
    },
    effectiveSettings: {
      llmModelOverride: { value: null, source: "default", activation: "next_workflow", editable: true },
      dailyBudgetUsd: { value: 20, source: "persisted", activation: "live", editable: true },
      applyConcurrency: { value: 1, source: "persisted", activation: "next_poll", editable: true },
      workerActivitySlots: { value: 4, source: "default", activation: "restart", editable: true },
      analysisLegs: { value: ["claude", "codex", "google"], source: "default", activation: "next_analysis", editable: true },
      tailoringGeneratorModels: { value: null, source: "default", activation: "next_workflow", editable: true },
      tailoringJudgeModel: { value: null, source: "default", activation: "next_workflow", editable: true },
      tailoringJudgeMinScore: { value: 0.82, source: "default", activation: "next_workflow", editable: true },
      applyMaxBudgetUsd: { value: 5, source: "default", activation: "next_apply_job", editable: true },
      applyTimeoutSeconds: { value: 900, source: "default", activation: "next_apply_job", editable: true },
      scoreCriteria: { value: "Synthetic demonstration criteria.", source: "persisted", activation: "next_run", editable: true },
      targetCriteria: { value: "Synthetic demonstration target.", source: "persisted", activation: "next_run", editable: true },
    },
    paths: { settingsPath: "browser-local demo settings" },
  },
  contacts: {
    list: {
      ok: true,
      items: [
        {
          contactId: "contact-demo-hiring-partner",
          displayName: "Synthetic hiring partner",
          role: "recruiter",
          employer: job.company,
          jobId: job.jobKey,
          attributeCount: 1,
          confirmedCount: 1,
          sourceKinds: ["user_entered"],
          allConfirmed: true,
          createdAt: at("2026-07-10T09:00:00.000Z"),
          updatedAt: at("2026-07-10T09:00:00.000Z"),
        },
      ],
    },
    details: {
      "contact-demo-hiring-partner": {
        ok: true,
        contact: {
          contactId: "contact-demo-hiring-partner",
          displayName: "Synthetic hiring partner",
          role: "recruiter",
          employer: job.company,
          jobId: job.jobKey,
          attributes: [
            {
              attributeId: "contact-demo-role",
              kind: "title",
              value: "Synthetic hiring partner",
              provenance: {
                sourceKind: "user_entered",
                sourceRef: "bundled-demo-fixture",
                captureMethod: "bundled_fixture",
                capturedAt: at("2026-07-10T09:00:00.000Z"),
                confidence: 1,
                userConfirmed: true,
              },
            },
          ],
          createdAt: at("2026-07-10T09:00:00.000Z"),
          updatedAt: at("2026-07-10T09:00:00.000Z"),
        },
      },
    },
    researchTasks: {
      ok: true,
      items: [
        {
          taskId: "research-demo-hiring-partner",
          employer: job.company,
          jobId: job.jobKey,
          status: "needs_review",
          candidateCount: 1,
          needsReviewCount: 1,
          confirmedCount: 0,
          startedAt: at("2026-07-11T08:40:00.000Z"),
          updatedAt: at("2026-07-11T08:45:00.000Z"),
          needsReviewAt: at("2026-07-11T08:45:00.000Z"),
          completedAt: null,
          failedAt: null,
          errorClass: null,
        },
      ],
    },
    researchTaskDetails: {
      "research-demo-hiring-partner": {
        ok: true,
        task: {
          taskId: "research-demo-hiring-partner",
          employer: job.company,
          jobId: job.jobKey,
          status: "needs_review",
          candidateCount: 1,
          needsReviewCount: 1,
          confirmedCount: 0,
          startedAt: at("2026-07-11T08:40:00.000Z"),
          updatedAt: at("2026-07-11T08:45:00.000Z"),
          needsReviewAt: at("2026-07-11T08:45:00.000Z"),
          completedAt: null,
          failedAt: null,
          errorClass: null,
          sourceAttempts: [
            {
              sourceKind: "bundled_fixture",
              sourceRef: "/demo/source-preview.html",
              outcome: "manual_capture_required",
              attemptedAt: at("2026-07-11T08:42:00.000Z"),
              detail: "Bundled fixture; no web request was made.",
            },
          ],
          candidates: [
            {
              candidateId: "candidate-demo-hiring-partner",
              taskId: "research-demo-hiring-partner",
              role: "recruiter",
              status: "needs_review",
              confidence: 0.5,
              provenance: {
                sourceKind: "user_entered",
                sourceRef: "bundled-demo-fixture",
                captureMethod: "bundled_fixture",
                capturedAt: at("2026-07-11T08:42:00.000Z"),
                confidence: 1,
                userConfirmed: false,
              },
              attributes: [
                {
                  attributeId: "candidate-demo-name",
                  kind: "name",
                  value: "Synthetic research candidate",
                  provenance: {
                    sourceKind: "user_entered",
                    sourceRef: "bundled-demo-fixture",
                    captureMethod: "bundled_fixture",
                    capturedAt: at("2026-07-11T08:42:00.000Z"),
                    confidence: 1,
                    userConfirmed: false,
                  },
                },
                {
                  attributeId: "candidate-demo-title",
                  kind: "title",
                  value: "Synthetic hiring partner",
                  provenance: {
                    sourceKind: "user_entered",
                    sourceRef: "bundled-demo-fixture",
                    captureMethod: "bundled_fixture",
                    capturedAt: at("2026-07-11T08:42:00.000Z"),
                    confidence: 1,
                    userConfirmed: false,
                  },
                },
              ],
              confirmedContactId: null,
              confirmedAt: null,
            },
          ],
        },
      },
    },
  },
  outreach: {
    thread: {
      ok: true,
      thread: {
        threadId: "thread-demo",
        contactId: "contact-demo-hiring-partner",
        jobId: job.jobKey,
        draftCount: 2,
        latestGeneration: 2,
        hasApprovedDraft: true,
        approvedDraftId: "outreach-draft-approved",
        latestStatus: "candidate",
        createdAt: at("2026-07-10T10:00:00.000Z"),
        updatedAt: at("2026-07-11T08:50:00.000Z"),
        drafts: [
          {
            draftId: "outreach-draft-approved",
            threadId: "thread-demo",
            generation: 1,
            kind: "intro_request",
            status: "approved",
            bodyText: "Bundled synthetic approved outreach draft.",
            gateResults: {
              passed: true,
              computedAgainst: "bundled synthetic draft",
              fabrications: [],
              validation: { passed: true, errors: [], warnings: [] },
              judge: { approved: true, score: 0.9, criterionScores: { grounding: 0.9 }, issues: [], notes: "Grounded synthetic draft." },
            },
            provenance: [
              {
                claimId: "outreach-claim-grounded",
                section: "opening",
                generatedText: "Bundled synthetic approved outreach draft.",
                contactFactIds: ["contact-demo-hiring-partner"],
                profileGrounded: true,
                rationale: "Bound to synthetic contact and evidence records.",
              },
            ],
            createdAt: at("2026-07-10T10:00:00.000Z"),
            approvedAt: at("2026-07-10T10:05:00.000Z"),
            rejectedAt: null,
            reason: "",
          },
          {
            draftId: "outreach-draft-candidate",
            threadId: "thread-demo",
            generation: 2,
            kind: "follow_up",
            status: "candidate",
            bodyText: "Bundled synthetic follow-up draft awaiting review.",
            gateResults: {
              passed: true,
              computedAgainst: "bundled synthetic draft",
              fabrications: [],
              validation: { passed: true, errors: [], warnings: [] },
              judge: { approved: true, score: 0.88, criterionScores: { grounding: 0.88 }, issues: [], notes: "Grounded synthetic draft." },
            },
            provenance: [],
            createdAt: at("2026-07-11T08:50:00.000Z"),
            approvedAt: null,
            rejectedAt: null,
            reason: "",
          },
        ],
        sendLogs: [],
        followUp: { state: "scheduled", dueAt: at("2026-07-12T09:00:00.000Z"), basis: "manual" },
        isSent: false,
      },
    },
    dueFollowUps: {
      ok: true,
      followUps: [
        {
          threadId: "thread-demo",
          contactId: "contact-demo-hiring-partner",
          jobId: job.jobKey,
          dueAt: at("2026-07-12T09:00:00.000Z"),
          basis: "manual",
          state: "scheduled",
          isDue: false,
        },
      ],
    },
  },
} satisfies DemoReadModel;
