"""Contact & Outreach bounded context — domain layer.

Phase 1: the ``Contact`` root. Phase 2: the supervised ``ContactResearchTask``
root, its source-access policy (INV-3), and the research/confirm use cases.
"""

from jobctrl.domain.contact.aggregate import Contact
from jobctrl.domain.contact.outreach import (
    FIRST_FOLLOW_UP_DAYS,
    SUBSEQUENT_NUDGE_DAYS,
    FollowUpBasis,
    FollowUpSchedule,
    FollowUpState,
    FollowUpSuggestion,
    OutreachDraft,
    OutreachDraftKind,
    OutreachSendLog,
    OutreachThread,
    follow_up_is_due,
    suggest_follow_up,
)
from jobctrl.domain.contact.outreach_gates import (
    DraftGateResults,
    OutreachClaimProvenance,
    build_outreach_evidence_corpus,
    build_outreach_judge_prompt,
    compute_outreach_claim_provenance,
    parse_outreach_judge_response,
    scan_outreach_draft,
    validate_outreach_draft,
)
from jobctrl.domain.contact.outreach_use_cases import (
    ApproveOutreachDraftUseCase,
    CompleteFollowUpUseCase,
    DismissFollowUpUseCase,
    GenerateOutreachDraftUseCase,
    LogOutreachSendUseCase,
    OutreachDraftInputError,
    OutreachFollowUpInputError,
    OutreachSendLogInputError,
    RejectOutreachDraftUseCase,
    ReviseOutreachDraftUseCase,
    ScheduleFollowUpUseCase,
)
from jobctrl.domain.contact.research import (
    CandidateStatus,
    ContactCandidate,
    ContactResearchTask,
    ResearchSourceAttempt,
    ResearchSourceOutcome,
    ResearchTaskStatus,
)
from jobctrl.domain.contact.research_services import (
    CANDIDATE_EXTRACTION_SCHEMA,
    ContactResearchService,
    ResearchRunResult,
    ResearchSourceSpec,
)
from jobctrl.domain.contact.research_use_cases import (
    ConfirmContactCandidateResult,
    ConfirmContactCandidateUseCase,
    ContactResearchInputError,
    RunContactResearchUseCase,
)
from jobctrl.domain.contact.source_policy import (
    CONTACT_RESEARCH_MANUAL_CAPTURE_MODES,
    RESEARCH_SOURCE_CATEGORIES,
    ContactResearchSourcePolicy,
    ResearchSourceCategory,
    ResearchSourceDecision,
    contact_research_source_policy,
    looks_protected,
)
from jobctrl.domain.contact.use_cases import (
    AttributeInput,
    ContactInputError,
    CreateContactUseCase,
    DeleteContactUseCase,
    ImportContactsUseCase,
    ImportResult,
    UpdateContactUseCase,
)
from jobctrl.domain.contact.value_objects import (
    CONTACT_CAPTURE_METHODS,
    CONTACT_SOURCE_KINDS,
    ContactAttribute,
    ContactFactProvenance,
    ContactLink,
    ContactRole,
    WarmIntroSignal,
)

__all__ = [
    "CANDIDATE_EXTRACTION_SCHEMA",
    "CONTACT_CAPTURE_METHODS",
    "CONTACT_RESEARCH_MANUAL_CAPTURE_MODES",
    "CONTACT_SOURCE_KINDS",
    "RESEARCH_SOURCE_CATEGORIES",
    "FIRST_FOLLOW_UP_DAYS",
    "SUBSEQUENT_NUDGE_DAYS",
    "ApproveOutreachDraftUseCase",
    "AttributeInput",
    "CandidateStatus",
    "CompleteFollowUpUseCase",
    "ConfirmContactCandidateResult",
    "ConfirmContactCandidateUseCase",
    "Contact",
    "ContactAttribute",
    "ContactCandidate",
    "ContactFactProvenance",
    "ContactInputError",
    "ContactLink",
    "ContactResearchInputError",
    "ContactResearchService",
    "ContactResearchSourcePolicy",
    "ContactResearchTask",
    "ContactRole",
    "CreateContactUseCase",
    "DeleteContactUseCase",
    "DismissFollowUpUseCase",
    "DraftGateResults",
    "FollowUpBasis",
    "FollowUpSchedule",
    "FollowUpState",
    "FollowUpSuggestion",
    "GenerateOutreachDraftUseCase",
    "ImportContactsUseCase",
    "ImportResult",
    "LogOutreachSendUseCase",
    "OutreachClaimProvenance",
    "OutreachDraft",
    "OutreachDraftInputError",
    "OutreachDraftKind",
    "OutreachFollowUpInputError",
    "OutreachSendLog",
    "OutreachSendLogInputError",
    "OutreachThread",
    "RejectOutreachDraftUseCase",
    "ReviseOutreachDraftUseCase",
    "ScheduleFollowUpUseCase",
    "follow_up_is_due",
    "suggest_follow_up",
    "build_outreach_evidence_corpus",
    "build_outreach_judge_prompt",
    "compute_outreach_claim_provenance",
    "parse_outreach_judge_response",
    "scan_outreach_draft",
    "validate_outreach_draft",
    "ResearchRunResult",
    "ResearchSourceAttempt",
    "ResearchSourceCategory",
    "ResearchSourceDecision",
    "ResearchSourceOutcome",
    "ResearchSourceSpec",
    "ResearchTaskStatus",
    "RunContactResearchUseCase",
    "UpdateContactUseCase",
    "WarmIntroSignal",
    "contact_research_source_policy",
    "looks_protected",
]
