import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { expect, type Locator, type Page, test } from "@playwright/test";

const repoRoot = path.resolve(
  fileURLToPath(new URL("../../../../", import.meta.url)),
);
const screenshotsDir = path.join(repoRoot, "docs", "assets", "screenshots");
const publicHeroScreenshotsDir = path.join(
  repoRoot,
  "docs",
  "public",
  "assets",
  "screenshots",
);
const heroScreenshotName = "dashboard.png";
const publicHeroScreenshotPath = path.join(
  publicHeroScreenshotsDir,
  heroScreenshotName,
);
const platformJobUrl =
  "https://boards.greenhouse.io/gitlab/jobs/qa-platform-director";
const platformJobId = encodeURIComponent(platformJobUrl);
const qaRunId = "qa-run-1";
const qaArtifactId = "qa-platform-resume-pdf";
const qaContactId = "qa-contact-hiring-manager";
const qaProfileImportFilename = "synthetic-platform-resume.pdf";
const qaProfileImportState = {
  state: {
    filename: qaProfileImportFilename,
    // Valid one-page synthetic PDF generated by the canonical QA fixture.
    // The screenshot workflow never sends it to the import endpoint.
    pdfBase64:
      "JVBERi0xLjQKJSBKb2JDdHJsIHN5bnRoZXRpYyBRQSBmaXh0dXJlCjEgMCBvYmoKPDwgL1R5cGUgL0NhdGFsb2cgL1BhZ2VzIDIgMCBSID4+CmVuZG9iagoyIDAgb2JqCjw8IC9UeXBlIC9QYWdlcyAvS2lkcyBbMyAwIFJdIC9Db3VudCAxID4+CmVuZG9iagozIDAgb2JqCjw8IC9UeXBlIC9QYWdlIC9QYXJlbnQgMiAwIFIgL01lZGlhQm94IFswIDAgNjEyIDc5Ml0gL1Jlc291cmNlcyA8PCAvRm9udCA8PCAvRjEgNCAwIFIgPj4gPj4gL0NvbnRlbnRzIDUgMCBSID4+CmVuZG9iago0IDAgb2JqCjw8IC9UeXBlIC9Gb250IC9TdWJ0eXBlIC9UeXBlMSAvQmFzZUZvbnQgL0hlbHZldGljYSA+PgplbmRvYmoKNSAwIG9iago8PCAvTGVuZ3RoIDU3ID4+CnN0cmVhbQpCVAovRjEgMTggVGYKNzIgNzIwIFRkCihTeW50aGV0aWMgcGxhdGZvcm0gcmVzdW1lKSBUagpFVAplbmRzdHJlYW0KZW5kb2JqCnhyZWYKMCA2CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDA0MCAwMDAwMCBuIAowMDAwMDAwMDg5IDAwMDAwIG4gCjAwMDAwMDAxNDYgMDAwMDAgbiAKMDAwMDAwMDI3MiAwMDAwMCBuIAowMDAwMDAwMzQyIDAwMDAwIG4gCnRyYWlsZXIKPDwgL1NpemUgNiAvUm9vdCAxIDAgUiA+PgpzdGFydHhyZWYKNDQ4CiUlRU9GCg==",
    importProfile: true,
    importStyle: true,
  },
  version: 1,
};
const jobsFilterParams =
  "stage=all&state=all&deleted=active&sort=fit_score&dir=desc&page=1&pageSize=50";
const jobDetailPath = `/jobs/${platformJobId}?${jobsFilterParams}`;
const jobRunTimelinePath = `/jobs/${platformJobId}/run/${qaRunId}?${jobsFilterParams}`;

interface ScreenshotSurface {
  readonly name: string;
  readonly path: string | ((page: Page) => Promise<string>);
  readonly proof: (page: Page) => Locator;
  readonly verify?: (page: Page) => Promise<void>;
  readonly viewport?: { readonly width: number; readonly height: number };
}

const defaultCaptureViewport = { width: 1440, height: 1000 } as const;
const profileCaptureViewport = { width: 1800, height: 1400 } as const;
const mobileCaptureViewport = { width: 390, height: 844 } as const;
const profileEditorWidth = 48;
let stagedScreenshotsDir: string | null = null;

const desktopSurfaces: readonly ScreenshotSurface[] = [
  {
    name: "dashboard.png",
    path: "/dashboard",
    proof: (page) => page.getByRole("heading", { name: "Dashboard" }),
  },
  {
    name: "analytics.png",
    path: "/analytics",
    proof: (page) => page.getByRole("heading", { name: "Outcome analytics" }),
  },
  {
    name: "jobs.png",
    path: `/jobs?${jobsFilterParams}`,
    proof: (page) => page.locator("table.jobs-data-grid-table"),
  },
  {
    name: "job-detail.png",
    path: jobDetailPath,
    proof: (page) => page.locator(".job-detail-workspace"),
  },
  {
    name: "job-run-timeline.png",
    path: jobRunTimelinePath,
    proof: (page) => page.locator(".job-run-workspace"),
  },
  {
    name: "apply-review.png",
    path: `/apply-review?jobKey=${platformJobId}`,
    proof: (page) =>
      page.getByRole("complementary", { name: "Application review queue" }),
  },
  {
    name: "pipelines.png",
    path: "/pipelines",
    proof: (page) =>
      page.getByRole("heading", { name: "Pipelines", exact: true }),
    verify: verifyPipelineOperations,
  },
  {
    name: "discovery.png",
    path: "/discovery",
    proof: (page) =>
      page.getByRole("heading", { name: "Discovery", exact: true }),
  },
  {
    name: "artifacts.png",
    path: "/artifacts",
    proof: (page) => page.locator("table.artifacts-data-grid-table"),
  },
  {
    name: "artifact-detail.png",
    path: `/artifacts/${qaArtifactId}`,
    proof: (page) => page.locator(".artifact-detail-workspace"),
    verify: async (page) => {
      const renderedPage = page.locator(".pdf-preview-pages img").first();
      await expect(renderedPage).toBeVisible({ timeout: 30_000 });
      await expect(renderedPage).toHaveAttribute("alt", /page 1$/);
      await expect(
        page.locator(".pdf-preview-toolbar .toolbar-status"),
      ).toHaveText("1 page");
    },
  },
  {
    name: "evidence-map.png",
    path: `/evidence-map?entry=ev-platform&job=${platformJobId}`,
    proof: (page) => page.locator(".evidence-map-view"),
  },
  {
    name: "contacts.png",
    path: "/outreach",
    proof: (page) => page.locator("table.contacts-data-grid-table"),
  },
  {
    name: "contact-detail.png",
    path: `/outreach/${qaContactId}`,
    proof: (page) => page.locator(".contact-detail-workspace"),
  },
  {
    name: "runs.png",
    path: "/runs",
    proof: (page) => page.locator("table.runs-data-grid-table"),
  },
  {
    name: "run-detail.png",
    path: `/runs/${qaRunId}`,
    proof: (page) => page.locator(".workflow-run-workspace"),
  },
  {
    name: "debug.png",
    path: "/debug",
    proof: (page) => page.getByRole("heading", { name: "Debug" }),
  },
  {
    name: "activity-detail.png",
    path: nonJobActivityDetailPath,
    proof: (page) => page.locator(".activity-detail-workspace"),
  },
  {
    name: "profile.png",
    path: "/profile",
    proof: (page) =>
      page.locator('[aria-label="Editable baseline resume page"]'),
    verify: verifyProfileFraming,
    viewport: profileCaptureViewport,
  },
  {
    name: "profile-import-upload.png",
    path: "/profile/import/upload",
    proof: (page) => page.getByText(qaProfileImportFilename, { exact: true }),
  },
  {
    name: "profile-import-preview.png",
    path: "/profile/import/preview",
    proof: (page) =>
      page
        .locator(".resume-import-selected-file")
        .getByText(qaProfileImportFilename, { exact: true }),
    verify: verifyProfileImportPreview,
  },
  {
    name: "profile-import-confirm.png",
    path: "/profile/import/confirm",
    proof: (page) => page.getByText(qaProfileImportFilename, { exact: true }),
    verify: verifyProfileImportConfirm,
  },
  {
    name: "preferences.png",
    path: "/preferences",
    proof: (page) => page.getByRole("heading", { name: "Preferences" }),
  },
  {
    name: "settings-general.png",
    path: "/settings",
    proof: (page) => page.getByRole("heading", { name: "Settings" }),
  },
  {
    name: "settings-credentials.png",
    path: "/settings/credentials",
    proof: (page) =>
      page.getByRole("heading", { name: "Settings", exact: true, level: 1 }),
    verify: verifyCredentialsCaptureReady,
  },
  {
    name: "settings-models.png",
    path: "/settings/models",
    proof: (page) =>
      page.getByRole("link", { name: "model selection", exact: true }),
    verify: async (page) => {
      await expect(
        page.getByRole("link", { name: "model selection", exact: true }),
      ).toHaveAttribute("aria-current", "page");
      await expect(page.locator(".model-selection-list")).toHaveAttribute(
        "aria-busy",
        "false",
      );
      await expect(page.getByText("Checking", { exact: true })).toHaveCount(0);
    },
  },
  {
    name: "settings-browser.png",
    path: "/settings/browser",
    proof: (page) =>
      page.getByRole("heading", { name: "Browser capabilities", exact: true }),
  },
];

const mobileSurfaces: readonly ScreenshotSurface[] = [
  {
    name: "dashboard-mobile.png",
    path: "/dashboard",
    proof: (page) => page.getByRole("heading", { name: "Dashboard" }),
    viewport: mobileCaptureViewport,
  },
  {
    name: "pipelines-mobile.png",
    path: "/pipelines",
    proof: (page) =>
      page.getByRole("heading", { name: "Pipelines", exact: true }),
    verify: verifyPipelineOperations,
    viewport: mobileCaptureViewport,
  },
  {
    name: "job-detail-mobile.png",
    path: jobDetailPath,
    proof: (page) => page.locator(".job-detail-workspace"),
    viewport: mobileCaptureViewport,
  },
  {
    name: "apply-review-mobile.png",
    path: `/apply-review?jobKey=${platformJobId}`,
    proof: (page) =>
      page.getByRole("complementary", { name: "Application review queue" }),
    viewport: mobileCaptureViewport,
  },
  {
    name: "profile-mobile.png",
    path: "/profile",
    proof: (page) =>
      page.locator('[aria-label="Editable baseline resume page"]'),
    viewport: mobileCaptureViewport,
  },
  {
    name: "settings-browser-mobile.png",
    path: "/settings/browser",
    proof: (page) =>
      page.getByRole("heading", { name: "Browser capabilities", exact: true }),
    viewport: mobileCaptureViewport,
  },
];

test.use({
  colorScheme: "light",
  viewport: defaultCaptureViewport,
});

test.beforeAll(async () => {
  await fs.mkdir(path.dirname(screenshotsDir), { recursive: true });
  await fs.mkdir(publicHeroScreenshotsDir, { recursive: true });
  stagedScreenshotsDir = await fs.mkdtemp(
    path.join(path.dirname(screenshotsDir), ".screenshots-stage-"),
  );
});

test.afterAll(async () => {
  if (stagedScreenshotsDir) {
    await fs.rm(stagedScreenshotsDir, { recursive: true, force: true });
    stagedScreenshotsDir = null;
  }
});

async function waitForRoute(page: Page, proof: Locator): Promise<void> {
  await expect(proof).toBeVisible({ timeout: 30_000 });
  await page.evaluate(() => document.fonts.ready);
  await page.waitForTimeout(250);
}

async function capture(page: Page, name: string): Promise<void> {
  if (!stagedScreenshotsDir) {
    throw new Error("Documentation screenshot staging is not initialized.");
  }
  const outputPath = path.join(stagedScreenshotsDir, name);
  await page.screenshot({
    animations: "disabled",
    path: outputPath,
  });
}

async function verifySyntheticSeedIdentity(page: Page): Promise<void> {
  const jobResponse = await page.request.get(`/v1/jobs/${platformJobId}`);
  expect(
    jobResponse.ok(),
    `Synthetic screenshot job is unavailable (${jobResponse.status()}).`,
  ).toBe(true);
  expect(await jobResponse.json()).toMatchObject({
    ok: true,
    job: {
      jobKey: platformJobUrl,
      title: "Director of Platform Engineering",
      fitScore: 9,
      descriptionPreview:
        "Lead platform security, reliability, and developer experience programs.",
    },
  });

  const operationsResponse = await page.request.get("/v1/pipeline/operations");
  expect(
    operationsResponse.ok(),
    `Synthetic operations snapshot is unavailable (${operationsResponse.status()}).`,
  ).toBe(true);
  expect(await operationsResponse.json()).toMatchObject({
    execution: {
      discoverWorkflowId: "discover-local",
      phase: "discovering",
    },
    sourceFamilies: { planned: 3 },
    capacity: { status: "available", activeSlots: 2 },
    activeItemsTotal: 2,
  });
}

async function publishStagedScreenshots(): Promise<void> {
  if (!stagedScreenshotsDir) {
    throw new Error("Documentation screenshot staging is not initialized.");
  }
  const expectedNames = [...desktopSurfaces, ...mobileSurfaces]
    .map((surface) => surface.name)
    .sort();
  const actualNames = (await fs.readdir(stagedScreenshotsDir))
    .filter((name) => name.endsWith(".png"))
    .sort();
  expect(actualNames).toEqual(expectedNames);

  const stagedDir = stagedScreenshotsDir;
  const backupDir = `${screenshotsDir}.backup-${process.pid}`;
  const nextHeroPath = `${publicHeroScreenshotPath}.next-${process.pid}`;
  await fs.rm(backupDir, { recursive: true, force: true });
  await fs.rm(nextHeroPath, { force: true });
  await fs.copyFile(path.join(stagedDir, heroScreenshotName), nextHeroPath);

  let previousGalleryMoved = false;
  let stagedGalleryPublished = false;
  try {
    try {
      await fs.rename(screenshotsDir, backupDir);
      previousGalleryMoved = true;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }

    await fs.rename(stagedDir, screenshotsDir);
    stagedScreenshotsDir = null;
    stagedGalleryPublished = true;
    await fs.rename(nextHeroPath, publicHeroScreenshotPath);
  } catch (error) {
    if (stagedGalleryPublished) {
      await fs.rename(screenshotsDir, stagedDir);
      stagedScreenshotsDir = stagedDir;
    }
    if (previousGalleryMoved) {
      await fs.rename(backupDir, screenshotsDir);
    }
    await fs.rm(nextHeroPath, { force: true });
    throw error;
  }

  if (previousGalleryMoved) {
    await fs.rm(backupDir, { recursive: true, force: true });
  }
}

async function nonJobActivityDetailPath(page: Page): Promise<string> {
  const response = await page.request.get(
    "/v1/debug/activity?page=1&pageSize=200&sort=occurred_at&dir=desc",
  );
  if (!response.ok()) {
    throw new Error(
      `Unable to load synthetic activity events (${response.status()}).`,
    );
  }
  const payload = (await response.json()) as {
    items?: Array<{ eventId?: string; jobKey?: string | null }>;
  };
  const event = payload.items?.find(
    (candidate) => !candidate.jobKey && candidate.eventId,
  );
  if (!event?.eventId) {
    throw new Error(
      "Synthetic screenshot seed must expose a non-job activity event.",
    );
  }

  // Local routes redirect job-linked events back to their owning job. Capture a
  // workflow event instead so this is a genuine direct Activity Detail route;
  // the demo-only direct-load feature flag is not enabled in the local E2E app.
  return `/activity/${encodeURIComponent(event.eventId)}`;
}

async function verifyPipelineOperations(page: Page): Promise<void> {
  for (const heading of [
    "Pipelines",
    "Live pipeline",
    "Source families and reconciliation",
    "Execution inspector",
    "Active work",
  ]) {
    await expect(page.getByRole("heading", { name: heading })).toBeVisible();
  }

  await expect(
    page.getByRole("group", { name: "Pipeline action tools" }),
  ).toBeVisible();

  await expect(page.getByText("1/3 succeeded", { exact: true })).toBeVisible();
  await expect(
    page.getByText("Enrichment pass", { exact: true }),
  ).toBeVisible();
  await expect(
    page.getByText("Preparation fanout", { exact: true }),
  ).toBeVisible();

  const response = await page.request.get("/v1/pipeline/operations");
  expect(
    response.ok(),
    `Unable to load seeded pipeline operations (${response.status()}).`,
  ).toBe(true);
  expect(await response.json()).toMatchObject({
    execution: {
      discoverWorkflowId: "discover-local",
      phase: "discovering",
    },
    sourceFamilies: {
      planned: 3,
      counts: {
        processing: 1,
        succeeded: 1,
        waiting: 1,
      },
    },
    capacity: {
      status: "available",
      activeSlots: 2,
    },
    activeItemsTotal: 2,
    activeItemsTruncated: false,
  });
}

async function verifyProfileFraming(page: Page): Promise<void> {
  const previewWorkbench = page.locator(".resume-editor-preview");
  const scrollPane = previewWorkbench.locator(".resume-plate-scroll");
  const resumePage = scrollPane.locator(".resume-plate-page");
  await expect(page.getByLabel("Full name", { exact: true })).toHaveValue(
    "John Doe",
  );
  await expect(page.getByLabel("Preferred name", { exact: true })).toHaveValue(
    "John",
  );
  await expect(page.getByLabel("Email", { exact: true })).toHaveValue(
    "john.doe@example.com",
  );
  await expect(resumePage).toContainText("John Doe");
  await expect(resumePage).toContainText("john.doe@example.com");
  const [previewWorkbenchBox, resumePageBox, scrollPaneBox, scrollMetrics] =
    await Promise.all([
      previewWorkbench.boundingBox(),
      resumePage.boundingBox(),
      scrollPane.boundingBox(),
      scrollPane.evaluate((element) => ({
        clientHeight: element.clientHeight,
        clientWidth: element.clientWidth,
        scrollHeight: element.scrollHeight,
        scrollWidth: element.scrollWidth,
        overflowX: getComputedStyle(element).overflowX,
        overflowY: getComputedStyle(element).overflowY,
      })),
    ]);

  expect(
    previewWorkbenchBox,
    "Profile resume preview workbench must have a capture box",
  ).not.toBeNull();
  expect(
    scrollPaneBox,
    "Profile resume scroll pane must have a capture box",
  ).not.toBeNull();
  expect(
    resumePageBox,
    "Profile A4 page must have a capture box",
  ).not.toBeNull();
  if (!previewWorkbenchBox || !scrollPaneBox || !resumePageBox) return;

  expect(scrollPaneBox.x).toBeGreaterThanOrEqual(previewWorkbenchBox.x);
  expect(scrollPaneBox.y).toBeGreaterThanOrEqual(previewWorkbenchBox.y);
  expect(resumePageBox.x).toBeGreaterThanOrEqual(scrollPaneBox.x);
  expect(resumePageBox.y).toBeGreaterThanOrEqual(scrollPaneBox.y);
  expect(scrollMetrics.overflowX).toBe("auto");
  expect(scrollMetrics.overflowY).toBe("auto");
  expect(scrollMetrics.scrollWidth).toBeGreaterThanOrEqual(
    scrollMetrics.clientWidth,
  );
  expect(scrollMetrics.scrollHeight).toBeGreaterThanOrEqual(
    scrollMetrics.clientHeight,
  );
}

async function verifyProfileImportPreview(page: Page): Promise<void> {
  await expect(
    page.getByRole("checkbox", { name: "Profile data" }),
  ).toBeChecked();
  await expect(
    page.getByRole("checkbox", { name: "Style data" }),
  ).toBeChecked();
}

async function verifyProfileImportConfirm(page: Page): Promise<void> {
  await expect(
    page.getByText("Profile and style", { exact: true }),
  ).toBeVisible();
}

async function verifyCredentialsCaptureReady(page: Page): Promise<void> {
  const settingsNavigation = page.getByRole("navigation", {
    name: "Settings sections",
  });
  const settingsTabs = settingsNavigation.getByRole("link");

  await expect(settingsNavigation).toBeVisible();
  await expect(settingsTabs).toHaveCount(4);
  for (const name of [
    "general",
    "credentials",
    "model selection",
    "Browser & extension",
  ]) {
    await expect(
      settingsNavigation.getByRole("link", { name, exact: true }),
    ).toBeVisible();
  }
  await expect(
    settingsNavigation.getByRole("link", {
      name: "credentials",
      exact: true,
    }),
  ).toHaveAttribute("aria-current", "page");

  await expect(
    page.getByRole("heading", { name: "LLM providers", exact: true, level: 2 }),
  ).toBeVisible();
  await expect(
    page.getByText("Checking provider setup.", { exact: true }),
  ).toBeHidden();
  for (const provider of ["Codex", "Claude", "Google"]) {
    await expect(
      page.getByRole("heading", { name: provider, exact: true, level: 3 }),
    ).toBeVisible();
  }

  await expect
    .poll(
      () =>
        settingsTabs.evaluateAll((tabs) =>
          tabs.every(
            (tab) =>
              tab.clientWidth > 0 &&
              tab.clientHeight > 0 &&
              tab.scrollWidth <= tab.clientWidth &&
              tab.scrollHeight <= tab.clientHeight,
          ),
        ),
      {
        message:
          "Settings tab labels must have stable, non-clipped geometry before capture",
      },
    )
    .toBe(true);
}

test("capture public documentation screenshots from synthetic seed data", async ({
  page,
}) => {
  test.setTimeout(120_000);
  test.skip(
    process.env.JOBCTRL_DOCS_SCREENSHOTS !== "1",
    "Rewrites docs/assets/screenshots — opt in via JOBCTRL_DOCS_SCREENSHOTS=1 (pnpm docs:screenshots sets it).",
  );
  await page.addInitScript(
    ({ key, value }) => window.localStorage.setItem(key, JSON.stringify(value)),
    { key: "jh:profile-preview-split-width", value: profileEditorWidth },
  );
  await page.addInitScript(
    ({ key, value }) => window.localStorage.setItem(key, JSON.stringify(value)),
    { key: "jh:profile-import", value: qaProfileImportState },
  );
  expect(
    desktopSurfaces,
    "The Product Tour requires 26 desktop capture surfaces.",
  ).toHaveLength(26);
  expect(
    mobileSurfaces,
    "The Product Tour requires 6 mobile capture surfaces.",
  ).toHaveLength(6);
  await verifySyntheticSeedIdentity(page);
  for (const surface of [...desktopSurfaces, ...mobileSurfaces]) {
    await page.setViewportSize(surface.viewport ?? defaultCaptureViewport);
    const route =
      typeof surface.path === "function"
        ? await surface.path(page)
        : surface.path;
    await page.goto(route);
    await waitForRoute(page, surface.proof(page));
    await surface.verify?.(page);
    await capture(page, surface.name);
  }
  await publishStagedScreenshots();
});
