import { expect, test } from "@playwright/test";
import { checkA11y, injectAxe } from "axe-playwright";
import { sampleInterviewCatalogResponse } from "../../src/test/fixtures/interviews.js";

const catalog = sampleInterviewCatalogResponse.catalog;

test("Interview atlas overview, topics, sources, history navigation and inspector", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  const errors: string[] = []; const jobReads: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); });
  page.on("request", (request) => { if (/\/v1\/jobs\/[^/?]+(?:\?|$)|generate-interview-prep/.test(request.url())) jobReads.push(request.url()); });
  await page.goto("/interviews?mode=graph");
  await expect(page).toHaveTitle(/Interviews/);
  const map = page.getByRole("region", { name: "Whole interview library graph" });
  await expect(map.locator("[data-graph-question-id]")).toHaveCount(121);
  await expect(map.locator(".interview-atlas__cluster")).toHaveCount(15);
  await expect(page.locator("vite-error-overlay")).toHaveCount(0);
  await page.screenshot({ path: "/tmp/jobctrl-993-ui-repair-desktop.png" });
  await injectAxe(page); await checkA11y(page, undefined, { includedImpacts: ["critical", "serious"] });
  await map.locator('[data-graph-question-id="B11"]').click();
  await expect(page).toHaveURL(/card=B11/);
  await expect(map.locator("[data-graph-question-id]")).toHaveCount(121);
  await page.getByRole("tab", { name: "Rubric", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Draft answer criteria" })).toBeVisible();
  await page.getByRole("tab", { name: "Sources", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Sources and reading limits" })).toBeVisible();
  const topic = catalog.topics[0]!;
  await map.getByRole("button", { name: `${topic.name}: ${topic.questionIds.length} questions` }).click();
  await expect(page).toHaveURL(new RegExp(`topic=${topic.id}`));
  await expect(map.locator(".interview-atlas__named-node")).toHaveCount(topic.questionIds.length);
  await page.goBack(); await expect(map.locator("[data-graph-question-id]")).toHaveCount(121);
  await page.goForward(); await expect(map.locator(".interview-atlas__named-node")).toHaveCount(topic.questionIds.length);
  await map.getByRole("button", { name: "Overview", exact: true }).click();
  await map.getByRole("button", { name: "Sources", exact: true }).click();
  await expect(map.locator("[data-graph-source-id]")).toHaveCount(57);
  await page.screenshot({ path: "/tmp/jobctrl-993-ui-repair-sources.png" });
  await map.locator('[data-graph-source-id="TR02"]').click();
  await expect(page.getByRole("region", { name: "Selected source" })).toContainText("The Staff Engineer's Path");
  await expect(map).toContainText("No linked questions in the current filters.");
  await map.getByRole("button", { name: "Overview", exact: true }).click();
  await map.getByRole("button", { name: "Questions", exact: true }).click();
  await map.getByRole("button", { name: "Zoom in" }).click();
  await expect(map).toContainText("120%");
  await map.getByRole("group", { name: "Interview graph canvas" }).focus();
  await page.keyboard.press("ArrowRight");
  await expect(map.locator(".interview-atlas__world")).toHaveCSS("transform", "matrix(1.2, 0, 0, 1.2, -40, 0)");
  await page.keyboard.press("Home"); await expect(map).toContainText("100%");
  await page.getByRole("button", { name: "List", exact: true }).click();
  await expect(page.getByRole("navigation", { name: "Interview questions" }).getByRole("link")).toHaveCount(121);
  await expect(page.locator(".interview-library__toolbar")).toHaveCSS("padding-top", "20px");
  expect(errors).toEqual([]); expect(jobReads).toEqual([]);
});

test("@mobile Interview atlas topic drill-down and readable inspector without overflow", async ({ page }) => {
  await page.goto("/interviews?mode=graph");
  const map = page.getByRole("region", { name: "Whole interview library graph" });
  await expect(map.locator(".interview-atlas__cluster")).toHaveCount(15);
  await page.screenshot({ path: "/tmp/jobctrl-993-ui-repair-mobile.png" });
  const topic = catalog.topics[0]!;
  await map.getByRole("button", { name: `${topic.name}: ${topic.questionIds.length} questions` }).click();
  await expect(map.locator(".interview-atlas__named-node")).toHaveCount(topic.questionIds.length);
  await map.locator(".interview-atlas__named-node").filter({ hasText: "C07" }).click();
  await expect(page).toHaveURL(/card=C07/);
  await page.getByRole("link", { name: "Read selected question ↓" }).click();
  await expect(page.getByRole("heading", { name: "What are your compensation expectations?", exact: true })).toBeInViewport();
  await expect(page.locator(".interview-question-detail")).toContainText(/budgeted range/i);
  await page.screenshot({ path: "/tmp/jobctrl-993-ui-repair-mobile-inspector.png" });
  await injectAxe(page); await checkA11y(page, undefined, { includedImpacts: ["critical", "serious"] });
  await page.setViewportSize({ width: 320, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await expect(page.getByRole("tab", { name: "Sources", exact: true })).toBeVisible();
});
